"""
codex.forge.reference_data.bitd_factions
=========================================
Blades in the Dark faction reference data — Doskvol organizations.
"""

FACTIONS = {
    # -- The Underworld --
    "The Billhooks": {
        "setting": "doskvol",
        "tier": 2, "hold": "strong",
        "description": "A tough gang of butchers and tanners, known for their brutal violence and their control of the meat trade.",
        "turf": "Charhollow slaughterhouses",
        "notable_npcs": ["Tarvul (leader)", "Coran (drug dealer)"],
        "quirk": "They use meat hooks as signature weapons.",
    },
    "The Crows": {
        "setting": "doskvol",
        "tier": 2, "hold": "strong",
        "description": "An old gang with a reputation for honor and fair dealing. They run gambling and protection rackets.",
        "turf": "Crow's Foot district",
        "notable_npcs": ["Roric (deposed leader, murdered)", "Lyssa (new leader)"],
        "quirk": "Internal power struggle after Roric's death.",
    },
    "The Hive": {
        "setting": "doskvol",
        "tier": 4, "hold": "strong",
        "description": "The largest criminal organization in Doskvol. They deal in drugs, contraband, and every vice imaginable.",
        "turf": "Widespread across several districts",
        "notable_npcs": ["Djera Maha (leader)", "Bell (second in command)"],
        "quirk": "Organized like a business with departments.",
    },
    "The Lampblacks": {
        "setting": "doskvol",
        "tier": 2, "hold": "weak",
        "description": "Former factory workers turned gang. They run protection and smuggling in Crow's Foot.",
        "turf": "Crow's Foot (contested)",
        "notable_npcs": ["Bazso Baz (leader)"],
        "quirk": "At war with the Red Sashes.",
    },
    "The Red Sashes": {
        "setting": "doskvol",
        "tier": 2, "hold": "weak",
        "description": "A group of noble-blooded sword-fighters who run vice and fencing operations.",
        "turf": "Crow's Foot (contested)",
        "notable_npcs": ["Mylera Klev (leader)"],
        "quirk": "Expert duelists, train daily at their sword academy.",
    },
    "The Wraiths": {
        "setting": "doskvol",
        "tier": 1, "hold": "weak",
        "description": "A small gang of thieves and pickpockets operating in Silkshore.",
        "turf": "Silkshore streets",
        "notable_npcs": ["Raven (leader)"],
        "quirk": "Specialize in jewel theft and confidence schemes.",
    },
    "The Gray Cloaks": {
        "setting": "doskvol",
        "tier": 2, "hold": "strong",
        "description": "Thieves and spies who traffic in secrets and blackmail material.",
        "turf": "Six Towers",
        "notable_npcs": ["Kruger (leader)"],
        "quirk": "Maintain extensive dossiers on powerful people.",
    },
    "Ulf Ironborn": {
        "setting": "doskvol",
        "tier": 1, "hold": "weak",
        "description": "A Skovlander refugee turned gang leader, fighting for his people.",
        "turf": "The Docks",
        "notable_npcs": ["Ulf Ironborn (leader)"],
        "quirk": "Loyal to displaced Skovlanders.",
    },

    # -- Institutions --
    "The Bluecoats": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "The city watch of Doskvol. Corrupt and brutal, they serve the interests of the wealthy.",
        "turf": "All districts",
        "notable_npcs": ["Commander Clelland", "Inspector Broya"],
        "quirk": "Can be bribed but have limits.",
    },
    "The Inspectors": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "The investigative branch of the government, more competent and less corrupt than the Bluecoats.",
        "turf": "Whitecrown HQ",
        "notable_npcs": ["Chief Inspector Lochlan"],
        "quirk": "Actually investigate crimes seriously.",
    },
    "The Spirit Wardens": {
        "setting": "doskvol",
        "tier": 4, "hold": "strong",
        "description": "The official keepers of the dead in Doskvol. They hunt rogue spirits and destroy undead.",
        "turf": "Bellweather Crematorium",
        "notable_npcs": ["Master Warden Vond"],
        "quirk": "Wear distinctive bronze masks.",
    },
    "The Ministry of Preservation": {
        "setting": "doskvol",
        "tier": 5, "hold": "strong",
        "description": "The Imperial bureaucracy that oversees the lightning barriers and essential city infrastructure.",
        "turf": "Government buildings, Whitecrown",
        "notable_npcs": ["Lord Governor Strangford"],
        "quirk": "Nearly untouchable politically.",
    },
    "The Leviathan Hunters": {
        "setting": "doskvol",
        "tier": 5, "hold": "strong",
        "description": "Brave crews that venture into the Void Sea to hunt the massive demons that swim there. Their blood fuels the lightning barriers.",
        "turf": "The Docks, open sea",
        "notable_npcs": ["Captain Laudius"],
        "quirk": "Revered and feared in equal measure.",
    },
    "Ironhook Prison": {
        "setting": "doskvol",
        "tier": 4, "hold": "strong",
        "description": "The notorious prison of Doskvol, where criminals are sent to hard labor or worse.",
        "turf": "Ironhook Island",
        "notable_npcs": ["Warden Hellyers"],
        "quirk": "Even guards fear certain cell blocks.",
    },
    "The City Council": {
        "setting": "doskvol",
        "tier": 5, "hold": "strong",
        "description": "The governing body of Doskvol. Composed of noble families and appointed officials.",
        "turf": "Charterhall, City Hall",
        "notable_npcs": ["Lord Scurlock (ancient vampire)", "Lady Drake"],
        "quirk": "Infested with vampires and worse.",
    },

    # -- The Arcane --
    "The Church of Ecstasy": {
        "setting": "doskvol",
        "tier": 4, "hold": "strong",
        "description": "The official state religion, devoted to forgotten gods and the comfort of the living in a bleak world.",
        "turf": "Temples in every district",
        "notable_npcs": ["Elder Rowan"],
        "quirk": "Actually provides genuine spiritual services.",
    },
    "The Path of Echoes": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "A secret society of occultists who commune with spirits and seek hidden truths.",
        "turf": "Hidden sanctums",
        "notable_npcs": ["The Reconciled (spirit collective)"],
        "quirk": "Spirits serve as members alongside the living.",
    },
    "The Dimmer Sisters": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "Three reclusive sisters who deal in spirits, ghosts, and dark artifacts from their estate in Six Towers.",
        "turf": "Six Towers estate",
        "notable_npcs": ["The three sisters (unnamed)"],
        "quirk": "No one has seen them clearly. Possibly not human.",
    },
    "The Forgotten Gods": {
        "setting": "doskvol",
        "tier": 4, "hold": "strong",
        "description": "A loose cult devoted to the ancient gods that existed before the Cataclysm shattered the world.",
        "turf": "Hidden shrines",
        "notable_npcs": ["Various cult leaders"],
        "quirk": "Genuinely powerful and genuinely mad.",
    },
    "The Reconciled": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "A secret society of ghosts who have retained their sanity and work to protect the living from supernatural threats.",
        "turf": "The ghost field",
        "notable_npcs": ["Kotar (ghost leader)"],
        "quirk": "Ghosts with purpose and organization.",
    },

    # -- Labor & Trade --
    "The Dockers": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "The dockworkers' union. Secretly a front for smuggling operations.",
        "turf": "The Docks",
        "notable_npcs": ["Steelbone Mike (union boss)"],
        "quirk": "Control who loads and unloads every ship.",
    },
    "The Gondoliers": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "The canal boat operators of Doskvol. They know every waterway and tunnel in the city.",
        "turf": "Canals and waterways",
        "notable_npcs": ["Eisele (guild master)"],
        "quirk": "Have arcane protections against the drowned.",
    },
    "The Ink Rakes": {
        "setting": "doskvol",
        "tier": 2, "hold": "weak",
        "description": "Journalists and pamphleteers who trade in scandal, gossip, and truth when convenient.",
        "turf": "Print shops in Charterhall",
        "notable_npcs": ["Kobb (editor)"],
        "quirk": "Information is their true currency.",
    },
    "The Cabbies": {
        "setting": "doskvol",
        "tier": 2, "hold": "strong",
        "description": "Carriage drivers who form an informal intelligence network across the city.",
        "turf": "Major thoroughfares",
        "notable_npcs": ["Old Nyelle (dispatcher)"],
        "quirk": "They overhear everything.",
    },
    "The Servants": {
        "setting": "doskvol",
        "tier": 2, "hold": "weak",
        "description": "A secret network of household servants who share intelligence about their noble employers.",
        "turf": "Noble estates",
        "notable_npcs": ["Quellyn (organizer)"],
        "quirk": "Invisible to those they serve.",
    },

    # -- Elite --
    "Lord Scurlock": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "An ancient vampire who poses as a reclusive noble. Controls vast wealth and dark secrets.",
        "turf": "Scurlock Manor, Six Towers",
        "notable_npcs": ["Lord Scurlock himself"],
        "quirk": "Has lived for centuries. Knows everything.",
    },
    "The Unseen": {
        "setting": "doskvol",
        "tier": 4, "hold": "strong",
        "description": "The most elite thieves' guild in Doskvol. Their existence is debated.",
        "turf": "Unknown",
        "notable_npcs": ["The Master (rumored leader)"],
        "quirk": "If you know about them, they know about you.",
    },
    "The Foundation": {
        "setting": "doskvol",
        "tier": 4, "hold": "strong",
        "description": "A secret society of elite aristocrats who manipulate city politics from the shadows.",
        "turf": "Private clubs in Whitecrown",
        "notable_npcs": ["Lord Strangford (patron)"],
        "quirk": "Members include the most powerful people in the city.",
    },
    "The Brigade": {
        "setting": "doskvol",
        "tier": 2, "hold": "strong",
        "description": "Firefighters who also run protection rackets. Pay them or watch it burn.",
        "turf": "Coalridge, Charhollow",
        "notable_npcs": ["Fire Chief Vale"],
        "quirk": "They start the fires they put out.",
    },
    "The Fog Hounds": {
        "setting": "doskvol",
        "tier": 1, "hold": "weak",
        "description": "A scrappy crew of smugglers who know the fog-shrouded canals better than anyone.",
        "turf": "Dunslough waterways",
        "notable_npcs": ["Captain Mira (leader)"],
        "quirk": "Specialize in moving people, not goods.",
    },
    "The Silver Nails": {
        "setting": "doskvol",
        "tier": 2, "hold": "strong",
        "description": "A mercenary company specializing in supernatural threats. They hunt ghosts for coin.",
        "turf": "Barracks in Charhollow",
        "notable_npcs": ["Commander Phin"],
        "quirk": "Their weapons are always silver-tipped.",
    },
    "The Circle of Flame": {
        "setting": "doskvol",
        "tier": 3, "hold": "strong",
        "description": "A secret society of wealthy elites who conduct forbidden arcane rituals.",
        "turf": "Private estates in Whitecrown",
        "notable_npcs": ["High Priest Volette"],
        "quirk": "Their rituals require living sacrifice.",
    },
}

# Faction relationship status levels
FACTION_STATUS = {
    -3: "War",
    -2: "Hostile",
    -1: "Interfering",
    0: "Neutral",
    1: "Helpful",
    2: "Friendly",
    3: "Allied",
}

__all__ = ["FACTIONS", "FACTION_STATUS"]
