"""
codex.forge.reference_data.dnd5e_spells_warlock
================================================
Warlock spell list for D&D 5e, levels 0-9.
Pact caster (spells known, short-rest slots). Source: PHB + SRD.

Levels 6, 7, 8, and 9 represent Mystic Arcanum spells — each is chosen
individually (one spell per tier, not a pool of slots). They are listed here
as a full reference pool for character creation selection.

SPELLS is keyed by spell level (int, 0 = cantrips).
"""

SPELLS: dict = {
    0: [  # Cantrips (choose 2, up to 4 at level 10)
        "Blade Ward",
        "Booming Blade",
        "Chill Touch",
        "Create Bonfire",
        "Eldritch Blast",
        "Friends",
        "Green-Flame Blade",
        "Lightning Lure",
        "Mage Hand",
        "Magic Stone",
        "Minor Illusion",
        "Poison Spray",
        "Prestidigitation",
        "Sword Burst",
        "Thunderclap",
        "Toll the Dead",
        "True Strike",
    ],
    1: [
        "Armor of Agathys",
        "Arms of Hadar",
        "Cause Fear",
        "Charm Person",
        "Comprehend Languages",
        "Expeditious Retreat",
        "Hellish Rebuke",
        "Hex",
        "Illusory Script",
        "Protection from Evil and Good",
        "Unseen Servant",
        "Witch Bolt",
    ],
    2: [
        "Cloud of Daggers",
        "Crown of Madness",
        "Darkness",
        "Earthbind",
        "Enthrall",
        "Hold Person",
        "Invisibility",
        "Mind Spike",
        "Mirror Image",
        "Misty Step",
        "Ray of Enfeeblement",
        "Shadow Blade",
        "Shatter",
        "Spider Climb",
        "Suggestion",
        "Web",
    ],
    3: [
        "Antagonize",
        "Counterspell",
        "Dispel Magic",
        "Enemies Abound",
        "Fear",
        "Fly",
        "Gaseous Form",
        "Hunger of Hadar",
        "Hypnotic Pattern",
        "Intellect Fortress",
        "Magic Circle",
        "Major Image",
        "Remove Curse",
        "Summon Fey",
        "Summon Lesser Demons",
        "Summon Shadowspawn",
        "Summon Undead",
        "Thunder Step",
        "Tongues",
        "Vampiric Touch",
    ],
    4: [
        "Banishment",
        "Blight",
        "Charm Monster",
        "Dimension Door",
        "Elemental Bane",
        "Hallucinatory Terrain",
        "Shadow of Moil",
        "Sickening Radiance",
        "Summon Aberration",
        "Summon Greater Demon",
        "Vitriolic Sphere",
        "Wall of Fire",
    ],
    5: [
        "Contact Other Plane",
        "Dream",
        "Enervation",
        "Far Step",
        "Hold Monster",
        "Infernal Calling",
        "Mislead",
        "Modify Memory",
        "Planar Binding",
        "Scrying",
        "Synaptic Static",
        "Teleportation Circle",
        "Wall of Light",
    ],
    6: [  # Mystic Arcanum (one spell chosen at warlock level 11)
        "Arcane Gate",
        "Circle of Death",
        "Create Undead",
        "Eyebite",
        "Flesh to Stone",
        "Investiture of Flame",
        "Investiture of Ice",
        "Investiture of Stone",
        "Investiture of Wind",
        "Mass Suggestion",
        "Mental Prison",
        "Scatter",
        "Soul Cage",
        "Tasha's Otherworldly Guise",
        "True Seeing",
    ],
    7: [  # Mystic Arcanum (one spell chosen at warlock level 13)
        "Crown of Stars",
        "Etherealness",
        "Finger of Death",
        "Forcecage",
        "Mordenkainen's Sword",
        "Plane Shift",
        "Power Word Pain",
        "Prismatic Spray",
        "Reverse Gravity",
        "Teleport",
        "Whirlwind",
    ],
    8: [  # Mystic Arcanum (one spell chosen at warlock level 15)
        "Abi-Dalzim's Horrid Wilting",
        "Demiplane",
        "Dominate Monster",
        "Feeblemind",
        "Glibness",
        "Maddening Darkness",
        "Power Word Stun",
        "Reality Break",
    ],
    9: [  # Mystic Arcanum (one spell chosen at warlock level 17)
        "Astral Projection",
        "Foresight",
        "Gate",
        "Imprisonment",
        "Power Word Kill",
        "Psychic Scream",
        "True Polymorph",
        "Weird",
    ],
}
