"""
codex.forge.reference_data.dnd5e_spells_druid
==============================================
Druid spell list for D&D 5e, levels 0-9.
Source: Player's Handbook (PHB), Xanathar's Guide to Everything (XGE),
        Tasha's Cauldron of Everything (TCE).

Druids are full casters (Wisdom-based, prepared).
Circle spells are NOT included here — this is the base class list only.
"""

SPELLS: dict = {
    0: [  # Cantrips
        "Druidcraft",
        "Guidance",
        "Mending",
        "Poison Spray",
        "Produce Flame",
        "Resistance",
        "Shillelagh",
        "Thorn Whip",
        "Thunderclap",
    ],
    1: [
        "Animal Friendship",
        "Beast Bond",
        "Charm Person",
        "Create or Destroy Water",
        "Cure Wounds",
        "Detect Magic",
        "Detect Poison and Disease",
        "Earth Tremor",
        "Entangle",
        "Faerie Fire",
        "Fog Cloud",
        "Goodberry",
        "Healing Word",
        "Ice Knife",
        "Jump",
        "Longstrider",
        "Purify Food and Drink",
        "Speak with Animals",
        "Thunderwave",
    ],
    2: [
        "Animal Messenger",
        "Barkskin",
        "Beast Sense",
        "Continual Flame",
        "Darkvision",
        "Dust Devil",
        "Earthbind",
        "Enhance Ability",
        "Find Traps",
        "Flame Blade",
        "Flaming Sphere",
        "Gust of Wind",
        "Heat Metal",
        "Hold Person",
        "Lesser Restoration",
        "Locate Animals or Plants",
        "Locate Object",
        "Moonbeam",
        "Pass Without Trace",
        "Protection from Poison",
        "Skywrite",
        "Spike Growth",
        "Summon Beast",
        "Warding Wind",
    ],
    3: [
        "Call Lightning",
        "Conjure Animals",
        "Daylight",
        "Dispel Magic",
        "Erupting Earth",
        "Feign Death",
        "Flame Arrows",
        "Meld into Stone",
        "Plant Growth",
        "Protection from Energy",
        "Revivify",
        "Sleet Storm",
        "Speak with Plants",
        "Summon Fey",
        "Tidal Wave",
        "Wall of Water",
        "Water Breathing",
        "Water Walk",
        "Wind Wall",
    ],
    4: [
        "Blight",
        "Confusion",
        "Conjure Minor Elementals",
        "Conjure Woodland Beings",
        "Control Water",
        "Dominate Beast",
        "Fire Shield",
        "Freedom of Movement",
        "Giant Insect",
        "Grasping Vine",
        "Guardian of Nature",
        "Hallucinatory Terrain",
        "Ice Storm",
        "Locate Creature",
        "Polymorph",
        "Stone Shape",
        "Stoneskin",
        "Summon Elemental",
        "Wall of Fire",
        "Watery Sphere",
    ],
    5: [
        "Antilife Shell",
        "Awaken",
        "Commune with Nature",
        "Conjure Elemental",
        "Contagion",
        "Control Winds",
        "Geas",
        "Greater Restoration",
        "Insect Plague",
        "Maelstrom",
        "Mass Cure Wounds",
        "Planar Binding",
        "Reincarnate",
        "Scrying",
        "Transmute Rock",
        "Tree Stride",
        "Wall of Stone",
        "Wrath of Nature",
    ],
    6: [
        "Conjure Fey",
        "Find the Path",
        "Flesh to Stone",
        "Heal",
        "Heroes' Feast",
        "Investiture of Flame",
        "Investiture of Ice",
        "Investiture of Stone",
        "Investiture of Wind",
        "Move Earth",
        "Primordial Ward",
        "Sunbeam",
        "Transport via Plants",
        "True Seeing",
        "Wall of Thorns",
        "Wind Walk",
    ],
    7: [
        "Fire Storm",
        "Mirage Arcane",
        "Plane Shift",
        "Regenerate",
        "Reverse Gravity",
        "Symbol",
        "Whirlwind",
    ],
    8: [
        "Animal Shapes",
        "Antipathy/Sympathy",
        "Control Weather",
        "Earthquake",
        "Feeblemind",
        "Sunburst",
        "Tsunami",
    ],
    9: [
        "Foresight",
        "Shapechange",
        "Storm of Vengeance",
        "True Resurrection",
    ],
}
