"""
codex.forge.reference_data.dnd5e_spells_wizard
===============================================
Wizard spell list for D&D 5e, levels 0-9.
Full caster (prepared from spellbook). Largest spell list in 5e.
Source: PHB + SRD + Xanathar's Guide + Tasha's Cauldron.

SPELLS is keyed by spell level (int, 0 = cantrips).
"""

SPELLS: dict = {
    0: [  # Cantrips (choose 3, up to 5 at level 10)
        "Acid Splash",
        "Blade Ward",
        "Booming Blade",
        "Chill Touch",
        "Control Flames",
        "Create Bonfire",
        "Dancing Lights",
        "Fire Bolt",
        "Frostbite",
        "Green-Flame Blade",
        "Gust",
        "Infestation",
        "Lightning Lure",
        "Light",
        "Mage Hand",
        "Mending",
        "Message",
        "Mind Sliver",
        "Minor Illusion",
        "Mold Earth",
        "Poison Spray",
        "Prestidigitation",
        "Ray of Frost",
        "Shape Water",
        "Shocking Grasp",
        "Sword Burst",
        "Thunderclap",
        "Toll the Dead",
        "True Strike",
    ],
    1: [
        "Absorb Elements",
        "Alarm",
        "Burning Hands",
        "Catapult",
        "Cause Fear",
        "Charm Person",
        "Chromatic Orb",
        "Color Spray",
        "Comprehend Languages",
        "Detect Magic",
        "Disguise Self",
        "Earth Tremor",
        "Expeditious Retreat",
        "False Life",
        "Feather Fall",
        "Find Familiar",
        "Fog Cloud",
        "Frost Fingers",
        "Grease",
        "Ice Knife",
        "Identify",
        "Illusory Script",
        "Jump",
        "Longstrider",
        "Mage Armor",
        "Magic Missile",
        "Protection from Evil and Good",
        "Ray of Sickness",
        "Shield",
        "Silent Image",
        "Sleep",
        "Snare",
        "Tasha's Hideous Laughter",
        "Tenser's Floating Disk",
        "Thunderwave",
        "Unseen Servant",
        "Witch Bolt",
    ],
    2: [
        "Aganazzar's Scorcher",
        "Alter Self",
        "Arcane Lock",
        "Blindness/Deafness",
        "Blur",
        "Cloud of Daggers",
        "Continual Flame",
        "Crown of Madness",
        "Darkness",
        "Darkvision",
        "Detect Thoughts",
        "Dragon's Breath",
        "Dust Devil",
        "Earthbind",
        "Enhance Ability",
        "Enlarge/Reduce",
        "Flaming Sphere",
        "Gentle Repose",
        "Hold Person",
        "Immovable Object",
        "Invisibility",
        "Knock",
        "Levitate",
        "Locate Object",
        "Magic Mouth",
        "Magic Weapon",
        "Melf's Acid Arrow",
        "Mind Spike",
        "Mirror Image",
        "Misty Step",
        "Nathair's Mischief",
        "Nystul's Magic Aura",
        "Phantasmal Force",
        "Pyrotechnics",
        "Ray of Enfeeblement",
        "Rope Trick",
        "Scorching Ray",
        "See Invisibility",
        "Shadow Blade",
        "Shatter",
        "Skywrite",
        "Snilloc's Snowball Swarm",
        "Spider Climb",
        "Suggestion",
        "Tasha's Mind Whip",
        "Vortex Warp",
        "Warding Wind",
        "Web",
        "Wristpocket",
    ],
    3: [
        "Animate Dead",
        "Bestow Curse",
        "Blink",
        "Clairvoyance",
        "Counterspell",
        "Dispel Magic",
        "Erupting Earth",
        "Fear",
        "Feign Death",
        "Fireball",
        "Flame Arrows",
        "Fly",
        "Gaseous Form",
        "Glyph of Warding",
        "Haste",
        "Hypnotic Pattern",
        "Intellect Fortress",
        "Leomund's Tiny Hut",
        "Lightning Bolt",
        "Magic Circle",
        "Major Image",
        "Melf's Minute Meteors",
        "Nondetection",
        "Phantom Steed",
        "Protection from Energy",
        "Remove Curse",
        "Sending",
        "Sleet Storm",
        "Slow",
        "Speak with Dead",
        "Spirit Shroud",
        "Stinking Cloud",
        "Summon Fey",
        "Summon Lesser Demons",
        "Summon Shadowspawn",
        "Summon Undead",
        "Thunder Step",
        "Tidal Wave",
        "Tiny Servant",
        "Tongues",
        "Vampiric Touch",
        "Wall of Sand",
        "Wall of Water",
        "Water Breathing",
    ],
    4: [
        "Arcane Eye",
        "Banishment",
        "Blight",
        "Charm Monster",
        "Confusion",
        "Conjure Minor Elementals",
        "Control Water",
        "Dimension Door",
        "Divination",
        "Elemental Bane",
        "Evard's Black Tentacles",
        "Fabricate",
        "Fire Shield",
        "Greater Invisibility",
        "Hallucinatory Terrain",
        "Ice Storm",
        "Leomund's Secret Chest",
        "Locate Creature",
        "Mordenkainen's Faithful Hound",
        "Mordenkainen's Private Sanctum",
        "Otiluke's Resilient Sphere",
        "Phantasmal Killer",
        "Polymorph",
        "Sickening Radiance",
        "Stone Shape",
        "Stoneskin",
        "Storm Sphere",
        "Summon Aberration",
        "Summon Construct",
        "Summon Elemental",
        "Summon Greater Demon",
        "Veil",
        "Vitriolic Sphere",
        "Wall of Fire",
        "Watery Sphere",
        "Widogast's Transmogrification",
    ],
    5: [
        "Animate Objects",
        "Bigby's Hand",
        "Cloudkill",
        "Cone of Cold",
        "Conjure Elemental",
        "Contact Other Plane",
        "Control Winds",
        "Creation",
        "Danse Macabre",
        "Dawn",
        "Dominate Person",
        "Dream",
        "Enervation",
        "Far Step",
        "Hold Monster",
        "Immolation",
        "Legend Lore",
        "Mislead",
        "Modify Memory",
        "Passwall",
        "Planar Binding",
        "Rary's Telepathic Bond",
        "Scrying",
        "Seeming",
        "Skill Empowerment",
        "Steel Wind Strike",
        "Summon Dragon",
        "Synaptic Static",
        "Telekinesis",
        "Teleportation Circle",
        "Transmute Rock",
        "Wall of Force",
        "Wall of Light",
        "Wall of Stone",
        "Yolande's Regal Presence",
    ],
    6: [
        "Arcane Gate",
        "Chain Lightning",
        "Circle of Death",
        "Contingency",
        "Create Homunculus",
        "Create Undead",
        "Disintegrate",
        "Drawmij's Instant Summons",
        "Eyebite",
        "Flesh to Stone",
        "Globe of Invulnerability",
        "Guards and Wards",
        "Investiture of Flame",
        "Investiture of Ice",
        "Investiture of Stone",
        "Investiture of Wind",
        "Magic Jar",
        "Mass Suggestion",
        "Mental Prison",
        "Move Earth",
        "Otiluke's Freezing Sphere",
        "Otto's Irresistible Dance",
        "Programmed Illusion",
        "Scatter",
        "Soul Cage",
        "Sunbeam",
        "Tasha's Otherworldly Guise",
        "True Seeing",
        "Wall of Ice",
    ],
    7: [
        "Crown of Stars",
        "Delayed Blast Fireball",
        "Dream of the Blue Veil",
        "Etherealness",
        "Finger of Death",
        "Forcecage",
        "Mirage Arcane",
        "Mordenkainen's Magnificent Mansion",
        "Mordenkainen's Sword",
        "Plane Shift",
        "Power Word Pain",
        "Prismatic Spray",
        "Project Image",
        "Reverse Gravity",
        "Sequester",
        "Simulacrum",
        "Symbol",
        "Teleport",
        "Tether Essence",
        "Whirlwind",
    ],
    8: [
        "Abi-Dalzim's Horrid Wilting",
        "Antimagic Field",
        "Antipathy/Sympathy",
        "Clone",
        "Control Weather",
        "Dark Star",
        "Demiplane",
        "Dominate Monster",
        "Feeblemind",
        "Illusory Dragon",
        "Incendiary Cloud",
        "Maddening Darkness",
        "Maze",
        "Mind Blank",
        "Power Word Stun",
        "Reality Break",
        "Sunburst",
        "Telepathy",
    ],
    9: [
        "Astral Projection",
        "Blade of Disaster",
        "Foresight",
        "Gate",
        "Imprisonment",
        "Invulnerability",
        "Mass Polymorph",
        "Meteor Swarm",
        "Power Word Kill",
        "Prismatic Wall",
        "Psychic Scream",
        "Shapechange",
        "Time Ravage",
        "Time Stop",
        "True Polymorph",
        "Weird",
        "Wish",
    ],
}
