"""
codex.forge.reference_data.dnd5e_spells_cleric
===============================================
Cleric spell list for D&D 5e, levels 0-9.
Source: Player's Handbook (PHB), Xanathar's Guide to Everything (XGE),
        Tasha's Cauldron of Everything (TCE).

Clerics are full casters (Wisdom-based, prepared).
Domain spells are NOT included here — this is the base class list only.
"""

SPELLS: dict = {
    0: [  # Cantrips
        "Guidance",
        "Light",
        "Mending",
        "Resistance",
        "Sacred Flame",
        "Spare the Dying",
        "Thaumaturgy",
        "Toll the Dead",
        "Word of Radiance",
    ],
    1: [
        "Bane",
        "Bless",
        "Command",
        "Create or Destroy Water",
        "Cure Wounds",
        "Detect Evil and Good",
        "Detect Magic",
        "Detect Poison and Disease",
        "Guiding Bolt",
        "Healing Word",
        "Inflict Wounds",
        "Protection from Evil and Good",
        "Purify Food and Drink",
        "Sanctuary",
        "Shield of Faith",
    ],
    2: [
        "Aid",
        "Augury",
        "Blindness/Deafness",
        "Calm Emotions",
        "Continual Flame",
        "Enhance Ability",
        "Find Traps",
        "Gentle Repose",
        "Hold Person",
        "Lesser Restoration",
        "Locate Object",
        "Prayer of Healing",
        "Protection from Poison",
        "Silence",
        "Spiritual Weapon",
        "Warding Bond",
        "Zone of Truth",
    ],
    3: [
        "Animate Dead",
        "Beacon of Hope",
        "Bestow Curse",
        "Clairvoyance",
        "Create Food and Water",
        "Daylight",
        "Dispel Magic",
        "Feign Death",
        "Glyph of Warding",
        "Magic Circle",
        "Mass Healing Word",
        "Meld into Stone",
        "Protection from Energy",
        "Remove Curse",
        "Revivify",
        "Sending",
        "Speak with Dead",
        "Spirit Guardians",
        "Tongues",
        "Water Walk",
    ],
    4: [
        "Banishment",
        "Control Water",
        "Death Ward",
        "Divination",
        "Freedom of Movement",
        "Guardian of Faith",
        "Locate Creature",
        "Stone Shape",
    ],
    5: [
        "Commune",
        "Contagion",
        "Dispel Evil and Good",
        "Flame Strike",
        "Geas",
        "Greater Restoration",
        "Hallow",
        "Insect Plague",
        "Legend Lore",
        "Mass Cure Wounds",
        "Planar Binding",
        "Raise Dead",
        "Scrying",
        "Summon Celestial",
    ],
    6: [
        "Blade Barrier",
        "Create Undead",
        "Find the Path",
        "Forbiddance",
        "Harm",
        "Heal",
        "Heroes' Feast",
        "Planar Ally",
        "True Seeing",
        "Word of Recall",
    ],
    7: [
        "Conjure Celestial",
        "Divine Word",
        "Etherealness",
        "Fire Storm",
        "Plane Shift",
        "Regenerate",
        "Resurrection",
        "Symbol",
    ],
    8: [
        "Antimagic Field",
        "Control Weather",
        "Earthquake",
        "Holy Aura",
    ],
    9: [
        "Astral Projection",
        "Gate",
        "Mass Heal",
        "True Resurrection",
    ],
}
