"""
codex.forge.reference_data.dnd5e_feats
=======================================
Hardcoded feat data from PHB, Xanathar's Guide, and Tasha's Cauldron.
"""

FEATS = {
    # ── PHB Feats ──────────────────────────────────────────────────────
    "alert": {
        "name": "Alert",
        "source": "PHB",
        "prereq": None,
        "description": "+5 initiative, can't be surprised while conscious",
    },
    "athlete": {
        "name": "Athlete",
        "source": "PHB",
        "prereq": None,
        "description": "+1 STR/DEX, standing from prone costs 5ft, climbing doesn't halve speed",
    },
    "actor": {
        "name": "Actor",
        "source": "PHB",
        "prereq": None,
        "description": "+1 CHA, advantage on Deception/Performance to pass as different person",
    },
    "charger": {
        "name": "Charger",
        "source": "PHB",
        "prereq": None,
        "description": "When you Dash, bonus action melee attack (+5 damage) or shove 10ft",
    },
    "crossbow_expert": {
        "name": "Crossbow Expert",
        "source": "PHB",
        "prereq": None,
        "description": "Ignore loading, no disadvantage in melee, bonus action hand crossbow attack",
    },
    "defensive_duelist": {
        "name": "Defensive Duelist",
        "source": "PHB",
        "prereq": "DEX 13+",
        "description": "Reaction: add proficiency bonus to AC vs one melee attack",
    },
    "dual_wielder": {
        "name": "Dual Wielder",
        "source": "PHB",
        "prereq": None,
        "description": "+1 AC with two weapons, use non-light weapons, draw/stow two weapons",
    },
    "dungeon_delver": {
        "name": "Dungeon Delver",
        "source": "PHB",
        "prereq": None,
        "description": "Advantage on trap detection/saves, search at normal pace, resistance to trap damage",
    },
    "durable": {
        "name": "Durable",
        "source": "PHB",
        "prereq": None,
        "description": "+1 CON, minimum HP from Hit Dice equals 2x CON modifier",
    },
    "elemental_adept": {
        "name": "Elemental Adept",
        "source": "PHB",
        "prereq": "Spellcasting",
        "description": "Choose element: spells ignore resistance, treat 1s as 2s on damage",
    },
    "grappler": {
        "name": "Grappler",
        "source": "PHB",
        "prereq": "STR 13+",
        "description": "Advantage on attacks vs grappled target, can pin to restrain both",
    },
    "great_weapon_master": {
        "name": "Great Weapon Master",
        "source": "PHB",
        "prereq": None,
        "description": "Bonus action attack on crit/kill, -5 attack/+10 damage option",
    },
    "healer": {
        "name": "Healer",
        "source": "PHB",
        "prereq": None,
        "description": "Healer's kit: stabilize + 1 HP, or heal 1d6+4+HD once per rest",
    },
    "heavily_armored": {
        "name": "Heavily Armored",
        "source": "PHB",
        "prereq": "Medium armor proficiency",
        "description": "+1 STR, heavy armor proficiency",
    },
    "heavy_armor_master": {
        "name": "Heavy Armor Master",
        "source": "PHB",
        "prereq": "Heavy armor proficiency",
        "description": "+1 STR, reduce nonmagical bludgeoning/piercing/slashing by 3",
    },
    "inspiring_leader": {
        "name": "Inspiring Leader",
        "source": "PHB",
        "prereq": "CHA 13+",
        "description": "10 min speech: up to 6 creatures gain level+CHA modifier temp HP",
    },
    "keen_mind": {
        "name": "Keen Mind",
        "source": "PHB",
        "prereq": None,
        "description": "+1 INT, know north/hours til sunrise/sunset, recall 1 month perfectly",
    },
    "lightly_armored": {
        "name": "Lightly Armored",
        "source": "PHB",
        "prereq": None,
        "description": "+1 STR/DEX, light armor proficiency",
    },
    "linguist": {
        "name": "Linguist",
        "source": "PHB",
        "prereq": None,
        "description": "+1 INT, learn 3 languages, create written ciphers",
    },
    "lucky": {
        "name": "Lucky",
        "source": "PHB",
        "prereq": None,
        "description": "3 luck points/day: reroll attack/ability/save or force reroll on attacker",
    },
    "mage_slayer": {
        "name": "Mage Slayer",
        "source": "PHB",
        "prereq": None,
        "description": "Reaction attack on adjacent caster, advantage on saves vs adjacent spells",
    },
    "magic_initiate": {
        "name": "Magic Initiate",
        "source": "PHB",
        "prereq": None,
        "description": "Learn 2 cantrips + 1 1st-level spell from chosen class",
    },
    "martial_adept": {
        "name": "Martial Adept",
        "source": "PHB",
        "prereq": None,
        "description": "Learn 2 maneuvers, gain 1 superiority die (d6)",
    },
    "medium_armor_master": {
        "name": "Medium Armor Master",
        "source": "PHB",
        "prereq": "Medium armor proficiency",
        "description": "No stealth disadvantage in medium armor, +3 DEX max instead of +2",
    },
    "mobile": {
        "name": "Mobile",
        "source": "PHB",
        "prereq": None,
        "description": "+10 speed, Dash ignores difficult terrain, no opportunity attack from melee target",
    },
    "moderately_armored": {
        "name": "Moderately Armored",
        "source": "PHB",
        "prereq": "Light armor proficiency",
        "description": "+1 STR/DEX, medium armor + shield proficiency",
    },
    "mounted_combatant": {
        "name": "Mounted Combatant",
        "source": "PHB",
        "prereq": None,
        "description": "Advantage vs smaller unmounted, redirect attacks to self, mount Evasion",
    },
    "observant": {
        "name": "Observant",
        "source": "PHB",
        "prereq": None,
        "description": "+1 INT/WIS, +5 passive Perception and Investigation, read lips",
    },
    "polearm_master": {
        "name": "Polearm Master",
        "source": "PHB",
        "prereq": None,
        "description": "Bonus action d4 butt end attack, opportunity attack when entering reach",
    },
    "resilient": {
        "name": "Resilient",
        "source": "PHB",
        "prereq": None,
        "description": "+1 to chosen ability, saving throw proficiency in that ability",
    },
    "ritual_caster": {
        "name": "Ritual Caster",
        "source": "PHB",
        "prereq": "INT or WIS 13+",
        "description": "Learn 2 1st-level ritual spells, can add more from scrolls",
    },
    "savage_attacker": {
        "name": "Savage Attacker",
        "source": "PHB",
        "prereq": None,
        "description": "Reroll melee weapon damage once per turn, use either roll",
    },
    "sentinel": {
        "name": "Sentinel",
        "source": "PHB",
        "prereq": None,
        "description": "Opportunity attack on Disengage, reaction attack when ally hit, speed to 0 on hit",
    },
    "sharpshooter": {
        "name": "Sharpshooter",
        "source": "PHB",
        "prereq": None,
        "description": "No disadvantage at long range, ignore cover, -5 attack/+10 damage option",
    },
    "shield_master": {
        "name": "Shield Master",
        "source": "PHB",
        "prereq": None,
        "description": "Bonus action shove with shield, add shield AC to DEX saves, Evasion for DEX saves",
    },
    "skilled": {
        "name": "Skilled",
        "source": "PHB",
        "prereq": None,
        "description": "Gain 3 skill or tool proficiencies",
    },
    "skulker": {
        "name": "Skulker",
        "source": "PHB",
        "prereq": "DEX 13+",
        "description": "Hide when lightly obscured, missed ranged doesn't reveal, dim light Perception normal",
    },
    "spell_sniper": {
        "name": "Spell Sniper",
        "source": "PHB",
        "prereq": "Spellcasting",
        "description": "Double spell range, ignore cover, learn one attack cantrip",
    },
    "tavern_brawler": {
        "name": "Tavern Brawler",
        "source": "PHB",
        "prereq": None,
        "description": "+1 STR/CON, improvised weapon proficiency, d4 unarmed, bonus action grapple",
    },
    "tough": {
        "name": "Tough",
        "source": "PHB",
        "prereq": None,
        "description": "+2 HP per level",
    },
    "war_caster": {
        "name": "War Caster",
        "source": "PHB",
        "prereq": "Spellcasting",
        "description": "Advantage on concentration, somatic with hands full, cantrip as opportunity attack",
    },
    "weapon_master": {
        "name": "Weapon Master",
        "source": "PHB",
        "prereq": None,
        "description": "+1 STR/DEX, gain 4 weapon proficiencies",
    },
    # ── XGE Racial Feats ──────────────────────────────────────────────
    "bountiful_luck": {
        "name": "Bountiful Luck",
        "source": "XGE",
        "prereq": "Halfling",
        "description": "When ally within 30ft rolls 1, use reaction to let them reroll",
    },
    "dragon_fear": {
        "name": "Dragon Fear",
        "source": "XGE",
        "prereq": "Dragonborn",
        "description": "+1 STR/CON/CHA, use breath weapon as fear (30ft, WIS save)",
    },
    "dragon_hide": {
        "name": "Dragon Hide",
        "source": "XGE",
        "prereq": "Dragonborn",
        "description": "+1 STR/CON/CHA, natural armor 13+DEX, retractable claws 1d4",
    },
    "drow_high_magic": {
        "name": "Drow High Magic",
        "source": "XGE",
        "prereq": "Elf (drow)",
        "description": "Detect Magic at will, Dispel Magic and Levitate 1/day each",
    },
    "dwarf_fortitude": {
        "name": "Dwarf Fortitude",
        "source": "XGE",
        "prereq": "Dwarf",
        "description": "+1 CON, when you Dodge you can spend a Hit Die to heal",
    },
    "elven_accuracy": {
        "name": "Elven Accuracy",
        "source": "XGE",
        "prereq": "Elf or Half-elf",
        "description": "+1 DEX/INT/WIS/CHA, triple advantage on attacks using those abilities",
    },
    "fade_away": {
        "name": "Fade Away",
        "source": "XGE",
        "prereq": "Gnome",
        "description": "+1 DEX/INT, reaction: turn invisible until end of next turn when damaged",
    },
    "fey_teleportation": {
        "name": "Fey Teleportation",
        "source": "XGE",
        "prereq": "Elf (high)",
        "description": "+1 INT/CHA, learn Sylvan, Misty Step 1/short rest",
    },
    "flames_of_phlegethos": {
        "name": "Flames of Phlegethos",
        "source": "XGE",
        "prereq": "Tiefling",
        "description": "+1 INT/CHA, reroll fire damage 1s, fire shield when casting fire spell",
    },
    "infernal_constitution": {
        "name": "Infernal Constitution",
        "source": "XGE",
        "prereq": "Tiefling",
        "description": "+1 CON, resistance to cold and poison damage, advantage vs poisoned",
    },
    "orcish_fury": {
        "name": "Orcish Fury",
        "source": "XGE",
        "prereq": "Half-orc",
        "description": "+1 STR/CON, extra weapon die 1/rest, bonus action attack on Relentless",
    },
    "prodigy": {
        "name": "Prodigy",
        "source": "XGE",
        "prereq": "Human, Half-elf, or Half-orc",
        "description": "1 skill proficiency, 1 tool proficiency, 1 language, 1 expertise",
    },
    "second_chance": {
        "name": "Second Chance",
        "source": "XGE",
        "prereq": "Halfling",
        "description": "+1 DEX/CON/CHA, force attacker to reroll 1/rest",
    },
    "squat_nimbleness": {
        "name": "Squat Nimbleness",
        "source": "XGE",
        "prereq": "Dwarf or Small race",
        "description": "+1 STR/DEX, +5 speed, Athletics/Acrobatics proficiency, advantage vs grapple",
    },
    "wood_elf_magic": {
        "name": "Wood Elf Magic",
        "source": "XGE",
        "prereq": "Elf (wood)",
        "description": "Learn 1 druid cantrip, Longstrider 1/day, Pass without Trace 1/day",
    },
    # ── TCE Feats ─────────────────────────────────────────────────────
    "artificer_initiate": {
        "name": "Artificer Initiate",
        "source": "TCE",
        "prereq": None,
        "description": "Learn 2 artificer cantrips + 1 1st-level artificer spell, tool proficiency",
    },
    "chef": {
        "name": "Chef",
        "source": "TCE",
        "prereq": None,
        "description": "+1 CON/WIS, cook treats for temp HP, short rest extra 1d8 healing",
    },
    "crusher": {
        "name": "Crusher",
        "source": "TCE",
        "prereq": None,
        "description": "+1 STR/CON, push 5ft on bludgeoning hit, crit grants advantage to all vs target",
    },
    "eldritch_adept": {
        "name": "Eldritch Adept",
        "source": "TCE",
        "prereq": "Spellcasting or Pact Magic",
        "description": "Learn one Eldritch Invocation",
    },
    "fey_touched": {
        "name": "Fey Touched",
        "source": "TCE",
        "prereq": None,
        "description": "+1 INT/WIS/CHA, Misty Step + 1 1st-level divination/enchantment 1/day",
    },
    "fighting_initiate": {
        "name": "Fighting Initiate",
        "source": "TCE",
        "prereq": "Martial weapon proficiency",
        "description": "Learn one Fighting Style from the fighter list",
    },
    "gunner": {
        "name": "Gunner",
        "source": "TCE",
        "prereq": None,
        "description": "+1 DEX, firearm proficiency, ignore loading, no disadvantage in melee",
    },
    "metamagic_adept": {
        "name": "Metamagic Adept",
        "source": "TCE",
        "prereq": "Spellcasting or Pact Magic",
        "description": "Learn 2 Metamagic options, gain 2 sorcery points for metamagic only",
    },
    "piercer": {
        "name": "Piercer",
        "source": "TCE",
        "prereq": None,
        "description": "+1 STR/DEX, reroll 1 piercing damage die, extra die on crit",
    },
    "poisoner": {
        "name": "Poisoner",
        "source": "TCE",
        "prereq": None,
        "description": "Ignore poison resistance, poisoner's kit proficiency, bonus action apply, craft potent poison",
    },
    "shadow_touched": {
        "name": "Shadow Touched",
        "source": "TCE",
        "prereq": None,
        "description": "+1 INT/WIS/CHA, Invisibility + 1 1st-level illusion/necromancy 1/day",
    },
    "skill_expert": {
        "name": "Skill Expert",
        "source": "TCE",
        "prereq": None,
        "description": "+1 any ability, 1 skill proficiency, 1 expertise in a skill",
    },
    "slasher": {
        "name": "Slasher",
        "source": "TCE",
        "prereq": None,
        "description": "+1 STR/DEX, reduce speed 10ft on slashing hit, crit gives disadvantage",
    },
    "telekinetic": {
        "name": "Telekinetic",
        "source": "TCE",
        "prereq": None,
        "description": "+1 INT/WIS/CHA, invisible Mage Hand 60ft, bonus action shove 5ft",
    },
    "telepathic": {
        "name": "Telepathic",
        "source": "TCE",
        "prereq": None,
        "description": "+1 INT/WIS/CHA, telepathy 60ft, Detect Thoughts 1/day",
    },
}
