"""
codex.forge.reference_data.dnd5e_personality
=============================================
Background personality tables (traits, ideals, bonds, flaws) for D&D 5e
character creation.  Each background provides 8 traits, 6 ideals, 6 bonds,
and 6 flaws per the PHB.
"""

PERSONALITY = {
    "acolyte": {
        "traits": [
            "I idolize a particular hero of my faith and constantly refer to their deeds.",
            "I can find common ground between the fiercest enemies, empathizing with them.",
            "I see omens in every event and action. The gods try to speak to us.",
            "Nothing can shake my optimistic attitude.",
            "I quote sacred texts and proverbs in almost every situation.",
            "I am tolerant or intolerant of other faiths and respect or condemn their worship.",
            "I have enjoyed fine food, drink, and high society. Rough living grates on me.",
            "I have spent so long in the temple that I have little practical experience.",
        ],
        "ideals": [
            "Tradition. Ancient rites must be preserved and upheld. (Lawful)",
            "Charity. I always try to help those in need. (Good)",
            "Change. We must help bring about the changes the gods are working in the world. (Chaotic)",
            "Power. I hope to one day rise to the top of my faith's hierarchy. (Lawful)",
            "Faith. I trust that my deity will guide my actions. (Lawful)",
            "Aspiration. I seek to prove myself worthy of my god's favor. (Any)",
        ],
        "bonds": [
            "I would do anything to recover an ancient relic of my faith that was lost long ago.",
            "I will someday get revenge on those who razed my temple.",
            "I owe my life to the priest who took me in when my parents perished.",
            "Everything I do is for the common people.",
            "I will do anything to protect the temple where I served.",
            "I seek to preserve a sacred text that my enemies seek to destroy.",
        ],
        "flaws": [
            "I judge others harshly, and myself even more severely.",
            "I put too much trust in those who wield power within my temple.",
            "My piety sometimes leads me to blindly trust those of my faith.",
            "I am inflexible in my thinking.",
            "I am suspicious of strangers and expect the worst of them.",
            "Once I pick a goal, I become obsessed with it to the detriment of everything else.",
        ],
    },
    "charlatan": {
        "traits": [
            "I fall in and out of love easily, and am always pursuing someone.",
            "I have a joke for every occasion, especially when humor is inappropriate.",
            "Flattery is my preferred trick for getting what I want.",
            "I am a born gambler who can't resist taking a risk for a potential payoff.",
            "I lie about almost everything, even when there is no reason to.",
            "Sarcasm and insults are my weapons of choice.",
            "I keep multiple holy symbols on me and invoke whatever deity might come in useful.",
            "I pocket anything I see that might have some value.",
        ],
        "ideals": [
            "Independence. I am a free spirit — no one tells me what to do. (Chaotic)",
            "Fairness. I never target people who can't afford to lose a few coins. (Lawful)",
            "Charity. I distribute the money I acquire to the people who really need it. (Good)",
            "Creativity. I never run the same con twice. (Chaotic)",
            "Friendship. Material goods come and go. Bonds of friendship last forever. (Good)",
            "Aspiration. I am determined to make something of myself. (Any)",
        ],
        "bonds": [
            "I fleeced the wrong person and must work to ensure they can never take revenge.",
            "I owe everything to my mentor — a terrible person who is probably rotting in jail.",
            "Somewhere out there I have a child who doesn't know me. I want to make a better world.",
            "I come from a noble family, and one day I will reclaim my lands and title.",
            "A powerful person ended someone I cared about. I seek to avenge them.",
            "I swindled a powerful person and now must stay one step ahead.",
        ],
        "flaws": [
            "I can't resist a pretty face.",
            "I am always in debt. I spend my ill-gotten gains on decadent luxuries.",
            "I am convinced that no one could ever fool me the way I fool others.",
            "I am too greedy for my own good. I can't resist taking a risk if money is involved.",
            "I can't resist swindling people who are more powerful than me.",
            "I hate to admit it and will hate myself for it, but I'll run to save my own skin.",
        ],
    },
    "criminal": {
        "traits": [
            "I always have a plan for what to do when things go wrong.",
            "I am always calm, no matter what the situation. I never raise my voice.",
            "The first thing I do in a new place is note the locations of everything valuable.",
            "I would rather make a new friend than a new enemy.",
            "I am incredibly slow to trust. Those who seem fairest often have the most to hide.",
            "I don't pay attention to the risks in a situation. Never tell me the odds.",
            "The best way to get me to do something is to tell me I can't do it.",
            "I blow up at the slightest insult.",
        ],
        "ideals": [
            "Honor. I don't steal from others in the trade. (Lawful)",
            "Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)",
            "Charity. I steal from the wealthy so that I can help people in need. (Good)",
            "Greed. I will do whatever it takes to become wealthy. (Neutral)",
            "People. I'm loyal to my friends, not to any ideal. (Neutral)",
            "Redemption. There's a spark of good in everyone. (Good)",
        ],
        "bonds": [
            "I'm trying to pay off a debt I owe to a generous benefactor.",
            "My ill-gotten gains go to support my family.",
            "Something important was taken from me, and I aim to get it back.",
            "I will become the greatest operative who ever lived.",
            "I'm guilty of a terrible mistake, and I hope I can redeem myself for it.",
            "Someone I loved was wrongly accused. I will clear their name.",
        ],
        "flaws": [
            "When I see something valuable, I think about how to acquire it.",
            "When faced with a choice between money and my friends, I usually choose money.",
            "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it.",
            "I have a tell that reveals when I am lying.",
            "I turn tail and run when things look bad.",
            "An innocent person is in prison for a crime that I committed, and I am okay with that.",
        ],
    },
    "entertainer": {
        "traits": [
            "I know a story relevant to almost every situation.",
            "Whenever I come to a new place, I collect local rumors and spread gossip.",
            "I am a hopeless romantic, always searching for that special someone.",
            "Nobody stays angry at me or around me for long, since I can defuse any tension.",
            "I love a good insult, even one directed at me.",
            "I get bitter if I am not the center of attention.",
            "I will settle for nothing less than perfection.",
            "I change my mood or my mind as quickly as I change key in a song.",
        ],
        "ideals": [
            "Beauty. When I perform, I make the world better than it was. (Good)",
            "Tradition. The stories and songs of the past must never be forgotten. (Lawful)",
            "Creativity. The world is in need of new ideas and bold action. (Chaotic)",
            "Greed. I am only in it for the money and fame. (Neutral)",
            "People. I like seeing the smiles on people's faces when I perform. (Neutral)",
            "Honesty. Art should reflect the soul; it should come from within. (Any)",
        ],
        "bonds": [
            "My instrument is my most treasured possession, a gift from someone dear.",
            "Someone stole my prized instrument, and someday I will get it back.",
            "I want to be famous, whatever it takes.",
            "I idolize a hero of the old tales and measure my deeds against theirs.",
            "I will do anything to prove myself superior to a hated rival.",
            "I would do anything for the other members of my old troupe.",
        ],
        "flaws": [
            "I will do anything to win fame and renown.",
            "I am a sucker for a pretty face.",
            "A scandal prevents me from ever going home again.",
            "I once satirized a noble who still wants my head. A foolish mistake.",
            "I have trouble keeping my true feelings hidden. My sharp tongue gets me in trouble.",
            "Despite my best efforts, I am unreliable to my friends.",
        ],
    },
    "folk_hero": {
        "traits": [
            "I judge people by their actions, not their words.",
            "If someone is in trouble, I am always ready to lend help.",
            "When I set my mind to something, I follow through no matter what.",
            "I have a strong sense of fair play and always try to find the most equitable solution.",
            "I am confident in my own abilities and do what I can to instill confidence in others.",
            "Thinking is for other people. I prefer action.",
            "I misuse long words in an attempt to sound smarter.",
            "I get bored easily. When am I going to get on with my destiny?",
        ],
        "ideals": [
            "Respect. People deserve to be treated with dignity and respect. (Good)",
            "Fairness. No one should get preferential treatment before the law. (Lawful)",
            "Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)",
            "Might. If I become strong, I can take what I want. (Neutral)",
            "Sincerity. There is no good in pretending to be something I am not. (Neutral)",
            "Destiny. Nothing and no one can steer me away from my higher calling. (Any)",
        ],
        "bonds": [
            "I have a family, but I have no idea where they are.",
            "I worked the land, I love the land, and I will protect the land.",
            "A proud noble once gave me a horrible beating, and I will take my revenge.",
            "My tools are symbols of my past life, and I carry them so I never forget.",
            "I protect those who cannot protect themselves.",
            "I wish my childhood sweetheart had come with me to pursue my destiny.",
        ],
        "flaws": [
            "I am convinced of the significance of my destiny, and blind to my faults.",
            "The people who knew me when I was young know a shameful secret about me.",
            "I have a weakness for the vices of the city, especially strong drink.",
            "Secretly, I believe that things would be better if I were a tyrant lording over the land.",
            "I have trouble trusting in my allies.",
            "I remember every insult I have received and nurse a silent resentment.",
        ],
    },
    "guild_artisan": {
        "traits": [
            "I believe that anything worth doing is worth doing right.",
            "I am a snob who looks down on those who can't appreciate fine art.",
            "I always want to know how things work and what makes people tick.",
            "I am full of witty aphorisms and have a proverb for every occasion.",
            "I am rude to people who lack my commitment to hard work and fair play.",
            "I like to talk at length about my profession.",
            "I don't part with my money easily and will haggle tirelessly for the best deal.",
            "I am well known for my work, and I want to make sure everyone appreciates it.",
        ],
        "ideals": [
            "Community. It is the duty of all people to strengthen community bonds. (Lawful)",
            "Generosity. My talents were given to me so I could use them to benefit the world. (Good)",
            "Freedom. Everyone should be free to pursue their own livelihood. (Chaotic)",
            "Greed. I am only in it for the money. (Neutral)",
            "People. I am committed to the people I care about, not to ideals. (Neutral)",
            "Aspiration. I work hard to be the best there is at my craft. (Any)",
        ],
        "bonds": [
            "The workshop where I learned my trade is the most important place in the world to me.",
            "I created a great work for someone, and then found them unworthy of it.",
            "I owe my guild a great debt for forging me into the person I am today.",
            "I pursue wealth to secure someone's love.",
            "One day I will return to my guild and prove that I am the greatest artisan of them all.",
            "I will get revenge on the evil forces that destroyed my place of business.",
        ],
        "flaws": [
            "I will do anything to get my hands on something rare or priceless.",
            "I am quick to assume that someone is trying to cheat me.",
            "No one must ever learn that I once stole money from guild coffers.",
            "I am never satisfied with what I have — I always want more.",
            "I would do anything for members of my old guild.",
            "I am horribly jealous of anyone who can outshine my handiwork.",
        ],
    },
    "hermit": {
        "traits": [
            "I have been isolated for so long that I rarely speak, preferring gestures.",
            "I am utterly serene, even in the face of disaster.",
            "The leader of my community had something wise to say on every topic.",
            "I feel tremendous empathy for all who are in pain.",
            "I am oblivious to etiquette and social expectations.",
            "I connect everything that happens to me to a grand, cosmic plan.",
            "I often get lost in my own thoughts and contemplation.",
            "I am working on a grand philosophical theory and love sharing my ideas.",
        ],
        "ideals": [
            "Greater Good. My gifts are meant to be shared with all, not hoarded. (Good)",
            "Logic. Emotions must not cloud our sense of what is right and true. (Lawful)",
            "Free Thinking. Inquiry and curiosity are the pillars of progress. (Chaotic)",
            "Power. Solitude and contemplation are paths toward mystical or magical power. (Neutral)",
            "Live and Let Live. Meddling in the affairs of others brings only trouble. (Neutral)",
            "Self-Knowledge. If you know yourself, there is nothing left to know. (Any)",
        ],
        "bonds": [
            "Nothing is more important than the other members of my hermitage or order.",
            "I entered seclusion to hide from those who might still be hunting me.",
            "I am still seeking the enlightenment I pursued in my seclusion.",
            "I entered seclusion because I loved someone I could not have.",
            "Should my discovery come to light, it could bring ruin to the world.",
            "My isolation gave me great insight into a great evil that threatens my land.",
        ],
        "flaws": [
            "Now that I have returned to the world, I enjoy its delights a little too much.",
            "I harbor dark, bloodthirsty thoughts that my isolation failed to quell.",
            "I am dogmatic in my thoughts and philosophy.",
            "I let my need to win arguments overshadow friendships.",
            "I would risk too much to uncover a lost bit of knowledge.",
            "I like keeping secrets and will not share them with anyone.",
        ],
    },
    "noble": {
        "traits": [
            "My eloquent flattery makes everyone I talk to feel wonderful and important.",
            "The common folk love me for my kindness and generosity.",
            "No one could doubt by looking at my regal bearing that I am above the unwashed masses.",
            "I take great pains to always look my best and follow the latest fashions.",
            "I don't like to get my hands dirty, and I won't be caught in unsuitable accommodations.",
            "Despite my noble birth, I do not place myself above other folk.",
            "I have a weakness for the new and exotic.",
            "If you do me an injury, I will crush you, ruin your name, and salt your fields.",
        ],
        "ideals": [
            "Respect. Respect is due to me because of my position, and to all regardless of station. (Good)",
            "Responsibility. It is my duty to respect the authority of those above me. (Lawful)",
            "Independence. I must prove that I can handle myself without coddling from family. (Chaotic)",
            "Power. If I can attain more power, no one will tell me what to do. (Neutral)",
            "Family. Blood runs thicker than water. (Any)",
            "Noble Obligation. It is my duty to protect and care for those beneath me. (Good)",
        ],
        "bonds": [
            "I will face any challenge to win the approval of my family.",
            "My house's alliance with another noble family must be sustained at all costs.",
            "Nothing is more important than the other members of my family.",
            "I am in love with the heir of a family that my family despises.",
            "My loyalty to my sovereign is unwavering.",
            "The common folk must see me as a hero of the people.",
        ],
        "flaws": [
            "I secretly believe that everyone is beneath me.",
            "I hide a truly scandalous secret that could ruin my family forever.",
            "I too often hear veiled insults and threats in every word addressed to me.",
            "I have an insatiable desire for carnal pleasures.",
            "In fact, the world does revolve around me.",
            "By my words and actions, I often bring shame to my family.",
        ],
    },
    "outlander": {
        "traits": [
            "I am driven by a wanderlust that led me away from home.",
            "I watch over my friends as if they were a litter of newborn pups.",
            "I once ran twenty-five miles without stopping to warn my clan of danger.",
            "I have a lesson for every situation, drawn from observing nature.",
            "I place no stock in wealthy or well-mannered folk.",
            "I was, in fact, raised by wolves.",
            "I feel far more comfortable around animals than people.",
            "I am always picking things up, absently fiddling with them, sometimes breaking them.",
        ],
        "ideals": [
            "Change. Life is like the seasons, in constant change, and we must change with it. (Chaotic)",
            "Greater Good. It is each person's responsibility to help the less fortunate. (Good)",
            "Honor. If I dishonor myself, I dishonor my whole clan. (Lawful)",
            "Might. The strongest are meant to rule. (Neutral)",
            "Nature. The natural world is more important than the constructs of civilization. (Neutral)",
            "Glory. I must earn glory in battle, for myself and my clan. (Any)",
        ],
        "bonds": [
            "My family, clan, or tribe is the most important thing in my life.",
            "An injury to the unspoiled wilderness of my home is an injury to me.",
            "I will bring terrible wrath down on those who destroyed my homeland.",
            "I am the last of my tribe, and it is up to me to ensure their names enter legend.",
            "I suffer awful visions of a coming disaster, and will do anything to prevent it.",
            "It is my duty to provide children to sustain my tribe.",
        ],
        "flaws": [
            "I am too enamored of ale, wine, and other intoxicants.",
            "There is no room for caution in a life lived to the fullest.",
            "I remember every insult I have received and nurse a silent resentment.",
            "I am slow to trust members of other races, tribes, or societies.",
            "Violence is my answer to almost any challenge.",
            "Don't expect me to save those who can't save themselves.",
        ],
    },
    "sage": {
        "traits": [
            "I use polysyllabic words that convey the impression of great erudition.",
            "I have read every book in the world's greatest libraries — or I like to boast I have.",
            "I am used to helping out those who are not as smart as I am.",
            "There is nothing I like more than a good mystery.",
            "I am willing to listen to every side of an argument before making my own judgment.",
            "I speak slowly when talking to anyone that is not as intelligent as I.",
            "I am horribly, horribly awkward in social situations.",
            "I am convinced that people are always trying to steal my secrets.",
        ],
        "ideals": [
            "Knowledge. The path to power and self-improvement is through knowledge. (Neutral)",
            "Beauty. What is beautiful points us beyond itself toward what is true. (Good)",
            "Logic. Emotions must not cloud our logical thinking. (Lawful)",
            "No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)",
            "Power. Knowledge is the path to power and domination. (Neutral)",
            "Self-Improvement. The goal of a life of study is the betterment of oneself. (Any)",
        ],
        "bonds": [
            "It is my duty to protect my students.",
            "I have an ancient text that holds terrible secrets. It must not fall into the wrong hands.",
            "I work to preserve a library, university, or scriptorium.",
            "My life's work is a series of tomes related to a specific field of lore.",
            "I have been searching my whole life for the answer to a certain question.",
            "I sold my soul for knowledge. I hope to do great deeds and win it back.",
        ],
        "flaws": [
            "I am easily distracted by the promise of information.",
            "Most people scream and run when they see a demon. I stop and take notes.",
            "Unlocking an ancient mystery is worth the price of a civilization.",
            "I overlook obvious solutions in favor of complicated ones.",
            "I speak without really thinking through my words, invariably insulting others.",
            "I can't keep a secret to save my life, or anyone else's.",
        ],
    },
    "sailor": {
        "traits": [
            "My friends know they can rely on me, no matter what.",
            "I work hard so that I can play hard when the work is done.",
            "I enjoy sailing into new ports and making new friends over drinks.",
            "I stretch the truth for the sake of a good story.",
            "To me, a tavern brawl is a nice way to get to know a new city.",
            "I never pass up a friendly wager.",
            "My language is as foul as an otyugh nest.",
            "I like a job well done, especially if I can convince others to do it.",
        ],
        "ideals": [
            "Respect. The thing that keeps a ship together is mutual respect. (Good)",
            "Fairness. We all do the work, so we all share in the rewards. (Lawful)",
            "Freedom. The sea is freedom — the freedom to go anywhere. (Chaotic)",
            "Mastery. I am a predator, and the other ships on the sea are my prey. (Neutral)",
            "People. I am committed to my crewmates, not to ideals. (Neutral)",
            "Aspiration. Someday I will own my own ship and chart my own destiny. (Any)",
        ],
        "bonds": [
            "I am loyal to my captain first, everything else second.",
            "The ship is most important — crewmates and captains come and go.",
            "I will always remember my first ship.",
            "In a harbor town, I have a paramour whose eyes nearly stole me from the sea.",
            "I was cheated out of my fair share of the profits, and I want to get my due.",
            "Ruthless pirates murdered my captain and crewmates. Vengeance will be mine.",
        ],
        "flaws": [
            "I follow orders, even if I think they are wrong.",
            "I will say anything to avoid having to do extra work.",
            "Once someone questions my courage, I never back down no matter how dangerous.",
            "Once I start drinking, it is hard for me to stop.",
            "I can't help but pocket loose coins and other trinkets I come across.",
            "My pride will probably lead to my destruction.",
        ],
    },
    "soldier": {
        "traits": [
            "I am always polite and respectful.",
            "I am haunted by memories of conflict. I can't get the images out of my mind.",
            "I have lost too many friends, and I am slow to make new ones.",
            "I am full of inspiring and cautionary tales from my experience.",
            "I can stare down a hell hound without flinching.",
            "I enjoy being strong and like breaking things.",
            "I have a crude sense of humor.",
            "I face problems head-on. A simple, direct solution is the best path.",
        ],
        "ideals": [
            "Greater Good. Our lot is to lay down our lives in defense of others. (Good)",
            "Responsibility. I do what I must and obey just authority. (Lawful)",
            "Independence. When people follow orders blindly, they embrace tyranny. (Chaotic)",
            "Might. In life as in war, the stronger force wins. (Neutral)",
            "Live and Let Live. Ideals are not worth fighting for. (Neutral)",
            "Nation. My city, nation, or people are all that matter. (Any)",
        ],
        "bonds": [
            "I would still lay down my life for the people I served with.",
            "Someone saved my life on the battlefield. To this day, I will never leave a friend.",
            "My honor is my life.",
            "I will never forget the crushing defeat my company suffered.",
            "Those who fight beside me are those worth protecting.",
            "I fight for those who cannot fight for themselves.",
        ],
        "flaws": [
            "The monstrous enemy we faced still leaves me quivering with fear.",
            "I have little respect for anyone who is not a proven warrior.",
            "I made a terrible mistake in battle that cost many lives.",
            "My hatred of my enemies is blind and unreasoning.",
            "I obey the law, even if the law causes misery.",
            "I would rather eat my armor than admit when I am wrong.",
        ],
    },
    "urchin": {
        "traits": [
            "I hide scraps of food and trinkets away in my pockets.",
            "I ask a lot of questions.",
            "I like to squeeze into small places where no one else can get to me.",
            "I sleep with my back to a wall or tree, with everything I own in a bundle.",
            "I eat like a pig and have bad manners.",
            "I think anyone who is nice to me is hiding dark intentions.",
            "I don't like to bathe.",
            "I bluntly say what other people are hinting at or hiding.",
        ],
        "ideals": [
            "Respect. All people, rich or poor, deserve respect. (Good)",
            "Community. We have to take care of each other, because no one else will. (Lawful)",
            "Change. The low are lifted up, and the high and mighty are brought down. (Chaotic)",
            "Retribution. The rich need to be shown what life and death are like. (Neutral)",
            "People. I help the people who help me — that is what keeps us alive. (Neutral)",
            "Aspiration. I am going to prove that I am worthy of a better life. (Any)",
        ],
        "bonds": [
            "My town or city is my home, and I will fight to defend it.",
            "I sponsor an orphanage to keep others from enduring what I was forced to endure.",
            "I owe my survival to another urchin who taught me to live on the streets.",
            "I owe a debt I can never repay to the person who took pity on me.",
            "I escaped my life of poverty by robbing an important person, and I am wanted.",
            "No one else should have to endure the hardships I have been through.",
        ],
        "flaws": [
            "If I am outnumbered, I will run away from a fight.",
            "Gold seems like a lot of money to me, and I will do just about anything for more.",
            "I will never fully trust anyone other than myself.",
            "I would rather use an underhanded tactic than fight fair.",
            "It is not stealing if I need it more than someone else.",
            "People who can't take care of themselves get what they deserve.",
        ],
    },
}
