"""
codex.forge.reference_data.dnd5e_spells_artificer
==================================================
Artificer spell list for D&D 5e, levels 0-5.
Half-caster (prepared from Intelligence). Source: Tasha's Cauldron of Everything.

Artificers prepare spells from their full list using the half-caster formula
(Artificer level / 2 + INT modifier). Spell slots also follow half-caster
progression, so the maximum spell slot level is 5.

SPELLS is keyed by spell level (int, 0 = cantrips).
"""

SPELLS: dict = {
    0: [  # Cantrips (choose 2 at level 1, gain a 3rd at level 10, 4th at level 14)
        "Acid Splash",
        "Create Bonfire",
        "Dancing Lights",
        "Fire Bolt",
        "Frostbite",
        "Guidance",
        "Light",
        "Mage Hand",
        "Magic Stone",
        "Mending",
        "Message",
        "Poison Spray",
        "Prestidigitation",
        "Ray of Frost",
        "Resistance",
        "Shocking Grasp",
        "Spare the Dying",
        "Thorn Whip",
        "Thunderclap",
    ],
    1: [
        "Absorb Elements",
        "Alarm",
        "Catapult",
        "Cure Wounds",
        "Detect Magic",
        "Disguise Self",
        "Expeditious Retreat",
        "Faerie Fire",
        "False Life",
        "Feather Fall",
        "Grease",
        "Identify",
        "Jump",
        "Longstrider",
        "Purify Food and Drink",
        "Sanctuary",
        "Snare",
        "Tasha's Caustic Brew",
    ],
    2: [
        "Aid",
        "Alter Self",
        "Arcane Lock",
        "Blur",
        "Continual Flame",
        "Darkvision",
        "Enhance Ability",
        "Enlarge/Reduce",
        "Heat Metal",
        "Invisibility",
        "Levitate",
        "Magic Mouth",
        "Magic Weapon",
        "Protection from Poison",
        "Pyrotechnics",
        "Rope Trick",
        "See Invisibility",
        "Skywrite",
        "Spider Climb",
        "Web",
    ],
    3: [
        "Blink",
        "Catnap",
        "Create Food and Water",
        "Dispel Magic",
        "Elemental Weapon",
        "Flame Arrows",
        "Fly",
        "Glyph of Warding",
        "Haste",
        "Intellect Fortress",
        "Magic Circle",
        "Protection from Energy",
        "Revivify",
        "Tiny Servant",
        "Water Breathing",
        "Water Walk",
    ],
    4: [
        "Arcane Eye",
        "Confusion",
        "Conjure Minor Elementals",
        "Death Ward",
        "Elemental Bane",
        "Fabricate",
        "Freedom of Movement",
        "Leomund's Secret Chest",
        "Mordenkainen's Faithful Hound",
        "Mordenkainen's Private Sanctum",
        "Otiluke's Resilient Sphere",
        "Stone Shape",
        "Stoneskin",
        "Summon Construct",
    ],
    5: [
        "Animate Objects",
        "Bigby's Hand",
        "Creation",
        "Greater Restoration",
        "Skill Empowerment",
        "Transmute Rock",
        "Wall of Stone",
    ],
}
