"""
codex.forge.reference_data.dnd5e_spells_sorcerer
=================================================
Sorcerer spell list for D&D 5e, levels 0-9.
Full caster (spells known). Source: PHB + SRD.

SPELLS is keyed by spell level (int, 0 = cantrips).
"""

SPELLS: dict = {
    0: [  # Cantrips (choose 4, up to 6 at level 10)
        "Acid Splash",
        "Blade Ward",
        "Chill Touch",
        "Dancing Lights",
        "Fire Bolt",
        "Friends",
        "Light",
        "Mage Hand",
        "Mending",
        "Message",
        "Minor Illusion",
        "Poison Spray",
        "Prestidigitation",
        "Ray of Frost",
        "Shocking Grasp",
        "Thunderclap",
        "True Strike",
    ],
    1: [
        "Burning Hands",
        "Catapult",
        "Chaos Bolt",
        "Charm Person",
        "Chromatic Orb",
        "Color Spray",
        "Comprehend Languages",
        "Detect Magic",
        "Disguise Self",
        "Earth Tremor",
        "Expeditious Retreat",
        "False Life",
        "Feather Fall",
        "Fog Cloud",
        "Ice Knife",
        "Jump",
        "Mage Armor",
        "Magic Missile",
        "Ray of Sickness",
        "Shield",
        "Silent Image",
        "Sleep",
        "Thunderwave",
        "Witch Bolt",
    ],
    2: [
        "Aganazzar's Scorcher",
        "Alter Self",
        "Blindness/Deafness",
        "Blur",
        "Cloud of Daggers",
        "Crown of Madness",
        "Darkness",
        "Darkvision",
        "Detect Thoughts",
        "Dragon's Breath",
        "Dust Devil",
        "Enhance Ability",
        "Enlarge/Reduce",
        "Gust of Wind",
        "Hold Person",
        "Invisibility",
        "Knock",
        "Levitate",
        "Magic Weapon",
        "Mirror Image",
        "Misty Step",
        "Phantasmal Force",
        "Pyrotechnics",
        "Scorching Ray",
        "See Invisibility",
        "Shatter",
        "Silk Rope",
        "Skywrite",
        "Spider Climb",
        "Suggestion",
        "Warding Wind",
        "Web",
    ],
    3: [
        "Blink",
        "Clairvoyance",
        "Counterspell",
        "Day Dreamer",
        "Dispel Magic",
        "Erupting Earth",
        "Fear",
        "Fireball",
        "Flame Arrows",
        "Fly",
        "Gaseous Form",
        "Haste",
        "Hypnotic Pattern",
        "Lightning Bolt",
        "Major Image",
        "Melf's Minute Meteors",
        "Protection from Energy",
        "Sleet Storm",
        "Slow",
        "Stinking Cloud",
        "Thunder Step",
        "Tidal Wave",
        "Tongues",
        "Vampiric Touch",
        "Wall of Water",
        "Water Breathing",
    ],
    4: [
        "Banishment",
        "Blight",
        "Charm Monster",
        "Confusion",
        "Dimension Door",
        "Dominate Beast",
        "Fire Shield",
        "Greater Invisibility",
        "Ice Storm",
        "Polymorph",
        "Sickening Radiance",
        "Storm Sphere",
        "Vitriolic Sphere",
        "Wall of Fire",
        "Watery Sphere",
        "Wimseyane Sword",
    ],
    5: [
        "Animate Objects",
        "Bigby's Hand",
        "Cloudkill",
        "Cone of Cold",
        "Control Winds",
        "Creation",
        "Dominate Person",
        "Enervation",
        "Far Step",
        "Hold Monster",
        "Immolation",
        "Insect Plague",
        "Seeming",
        "Skill Empowerment",
        "Synaptic Static",
        "Telekinesis",
        "Transmute Rock",
        "Wall of Light",
        "Wall of Stone",
    ],
    6: [
        "Arcane Gate",
        "Chain Lightning",
        "Circle of Death",
        "Disintegrate",
        "Eyebite",
        "Globe of Invulnerability",
        "Investiture of Flame",
        "Investiture of Ice",
        "Investiture of Stone",
        "Investiture of Wind",
        "Magic Jar",
        "Mass Suggestion",
        "Mental Prison",
        "Move Earth",
        "Otiluke's Freezing Sphere",
        "Scatter",
        "Soul Cage",
        "Sunbeam",
        "True Seeing",
    ],
    7: [
        "Delayed Blast Fireball",
        "Etherealness",
        "Finger of Death",
        "Fire Storm",
        "Forcecage",
        "Plane Shift",
        "Prismatic Spray",
        "Reverse Gravity",
        "Sequester",
        "Simulacrum",
        "Teleport",
        "Whirlwind",
    ],
    8: [
        "Abi-Dalzim's Horrid Wilting",
        "Dominate Monster",
        "Earthquake",
        "Incendiary Cloud",
        "Power Word Stun",
        "Sunburst",
        "Telepathy",
    ],
    9: [
        "Gate",
        "Meteor Swarm",
        "Power Word Kill",
        "Time Stop",
        "True Polymorph",
        "Wish",
    ],
}
