#!/usr/bin/env python3
"""
codex/spatial/zone_loader.py - Zone Loader
==========================================

Bridges ZoneEntry manifests to the CodexMapEngine, producing DungeonGraph
objects ready for content injection and rendering.

Blueprint zones: geometry loaded verbatim from a hand-authored JSON file.
Procedural zones: geometry generated by CodexMapEngine using generation_params.

The loader is intentionally stateless — instantiate once per module session
with the base_path for blueprint resolution, then call ``load_zone()`` as
many times as needed.

Version: 1.0
"""

from __future__ import annotations

import json
import logging
import os
from typing import Optional

from codex.spatial.map_engine import CodexMapEngine, DungeonGraph, GenerationMode
from codex.spatial.module_manifest import ZoneEntry

logger = logging.getLogger(__name__)


# =============================================================================
# TOPOLOGY -> GENERATION MODE MAPPING
# =============================================================================

_TOPOLOGY_TO_MODE: dict = {
    "dungeon":    GenerationMode.DUNGEON,
    "wilderness": GenerationMode.WILDERNESS,
    "vertical":   GenerationMode.VERTICAL,
    "settlement": GenerationMode.SETTLEMENT,
}

# Default generation parameters when ZoneEntry.generation_params is None or
# missing individual keys.
_DEFAULTS: dict = {
    "width":           50,
    "height":          50,
    "max_depth":       4,
    "seed":            None,   # None means CodexMapEngine picks a random seed
    # Wilderness-specific
    "room_count":      10,
    "min_room_size":   4,
    "max_room_size":   10,
    # Vertical-specific
    "floors":          6,
    "rooms_per_floor": 2,
    "floor_width":     30,
    "floor_height":    8,
    # Settlement-specific
    "building_count":  8,
}


# =============================================================================
# ZONE LOADER
# =============================================================================

class ZoneLoader:
    """Bridges ZoneEntry manifests to CodexMapEngine for zone generation.

    Attributes:
        base_path: Root directory for resolving relative blueprint paths.
                   If empty, blueprint paths are interpreted as given.
    """

    def __init__(self, base_path: str = "") -> None:
        """Initialise the loader.

        Args:
            base_path: Directory root used to resolve relative blueprint paths.
                       Typically the directory containing the module manifest.
        """
        self.base_path = base_path

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def load_zone(self, entry: ZoneEntry) -> DungeonGraph:
        """Load or generate a zone based on its ZoneEntry configuration.

        Dispatch logic:
            - If ``entry.blueprint`` is set  -> ``load_blueprint()``
            - Otherwise                       -> ``generate_procedural()``

        The resulting DungeonGraph has its ``metadata`` field populated with
        zone-level info (zone_id, theme, topology, location_id) for downstream
        consumers (e.g. the renderer).

        Args:
            entry: ZoneEntry descriptor from the module manifest.

        Returns:
            DungeonGraph with geometry (and metadata) filled in.
        """
        if entry.blueprint:
            logger.debug("ZoneLoader: loading blueprint '%s'", entry.blueprint)
            graph = self.load_blueprint(entry.blueprint)
        else:
            logger.debug("ZoneLoader: generating procedural zone '%s'", entry.zone_id)
            graph = self.generate_procedural(entry)

        # Stamp zone-level metadata onto the graph for rendering/content layers.
        graph.metadata = {
            "zone_id":     entry.zone_id,
            "theme":       entry.theme,
            "topology":    entry.topology,
            "location_id": entry.location_id,
        }
        return graph

    def load_blueprint(self, path: str) -> DungeonGraph:
        """Load a hand-authored zone blueprint from a JSON file.

        The file format is DungeonGraph.to_dict() output with two optional
        extra keys:
            ``metadata``      -- zone-level info dict
            ``content_hints`` -- per-room NPC/service hints keyed by room ID

        ``content_hints`` at the top level are distributed onto individual
        RoomNode.content_hints fields so adapters can access them without
        knowing the JSON structure.

        Path resolution: if *path* is relative it is joined with
        ``self.base_path``.

        Args:
            path: Path to the blueprint JSON file.

        Returns:
            DungeonGraph reconstructed from the blueprint.

        Raises:
            FileNotFoundError: If the resolved path does not exist.
            json.JSONDecodeError: If the file is malformed JSON.
        """
        resolved = self._resolve_path(path)
        if not os.path.isfile(resolved):
            raise FileNotFoundError(
                f"ZoneLoader: blueprint not found at '{resolved}'"
            )

        with open(resolved, "r", encoding="utf-8") as fh:
            data = json.load(fh)

        graph = DungeonGraph.from_dict(data)

        # Distribute top-level content_hints (keyed by str room ID) onto rooms.
        top_level_hints: dict = data.get("content_hints", {})
        for room_id_str, hints in top_level_hints.items():
            room_id = int(room_id_str)
            room = graph.rooms.get(room_id)
            if room is not None and room.content_hints is None:
                room.content_hints = hints

        logger.info(
            "ZoneLoader: loaded blueprint '%s' — %d rooms", resolved, len(graph.rooms)
        )
        return graph

    def generate_procedural(self, entry: ZoneEntry) -> DungeonGraph:
        """Generate a procedural zone from a ZoneEntry's generation_params.

        Reads ``entry.generation_params`` (overriding module defaults) and
        dispatches to the appropriate CodexMapEngine generator method based on
        ``entry.topology``.

        Topology -> generator mapping:
            dungeon    -> CodexMapEngine.generate()
            wilderness -> CodexMapEngine.generate_wilderness()
            vertical   -> CodexMapEngine.generate_vertical()
            settlement -> CodexMapEngine.generate_settlement()

        Args:
            entry: ZoneEntry with topology and optional generation_params.

        Returns:
            DungeonGraph with procedurally generated geometry.
        """
        params = dict(_DEFAULTS)
        if entry.generation_params:
            params.update(entry.generation_params)

        seed: Optional[int] = params.get("seed")
        engine = CodexMapEngine(seed=seed)

        topology = entry.topology.lower()
        graph: DungeonGraph

        if topology == "dungeon":
            graph = engine.generate(
                width=int(params["width"]),
                height=int(params["height"]),
                max_depth=int(params["max_depth"]),
            )
        elif topology == "wilderness":
            graph = engine.generate_wilderness(
                width=int(params["width"]),
                height=int(params["height"]),
                room_count=int(params["room_count"]),
                min_room_size=int(params["min_room_size"]),
                max_room_size=int(params["max_room_size"]),
            )
        elif topology == "vertical":
            graph = engine.generate_vertical(
                floors=int(params["floors"]),
                rooms_per_floor=int(params["rooms_per_floor"]),
                floor_width=int(params["floor_width"]),
                floor_height=int(params["floor_height"]),
            )
        elif topology == "settlement":
            graph = engine.generate_settlement(
                width=int(params["width"]),
                height=int(params["height"]),
                building_count=int(params["building_count"]),
            )
        else:
            # Unknown topology — fall back to dungeon with a warning.
            logger.warning(
                "ZoneLoader: unknown topology '%s' for zone '%s', "
                "falling back to dungeon generation.",
                topology, entry.zone_id,
            )
            graph = engine.generate(
                width=int(params["width"]),
                height=int(params["height"]),
                max_depth=int(params["max_depth"]),
            )

        logger.info(
            "ZoneLoader: generated procedural %s zone '%s' — %d rooms "
            "(seed=%d)",
            topology, entry.zone_id, len(graph.rooms), engine.seed,
        )
        return graph

    # ------------------------------------------------------------------
    # Rendering hint
    # ------------------------------------------------------------------

    @staticmethod
    def get_theme(entry: ZoneEntry) -> str:
        """Return the MapTheme name for rendering this zone.

        Args:
            entry: ZoneEntry whose ``theme`` field is used.

        Returns:
            Theme name string (e.g. "RUST", "STONE", "GOTHIC").
        """
        return entry.theme.upper()

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _resolve_path(self, path: str) -> str:
        """Resolve a possibly-relative blueprint path against self.base_path.

        Args:
            path: Raw path string from the manifest.

        Returns:
            Absolute path string.
        """
        if os.path.isabs(path) or not self.base_path:
            return path
        return os.path.join(self.base_path, path)
