"""
Engine scaffolder: reads system manifest, generates engine code + tests.

Usage:
    python scripts/scaffold_engine.py <system_id>

Reads (in priority order):
    1. codex/games/{system_id}/system_manifest.json
    2. vault/{system_id}/system_manifest.json
    3. vault/**/{system_id}/system_manifest.json  (recursive search)

Generates:
    1. codex/games/{system_id}/__init__.py  — engine subclass
    2. config/bestiary/{system_id}.json     — empty template
    3. config/loot/{system_id}.json         — empty template
    4. tests/test_{system_id}_engine.py     — smoke tests

All generated files have the header:
    # AUTO-GENERATED by scaffold_engine.py -- customize below

Exit codes:
    0  Success
    1  Manifest not found
    2  Engine file already exists (use --force to overwrite)
"""

from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path
from textwrap import dedent
from typing import Any, Dict, List, Optional, Tuple

# ---------------------------------------------------------------------------
# Project root (scripts/ is one level below project root)
# ---------------------------------------------------------------------------
_SCRIPT_DIR = Path(__file__).resolve().parent
_PROJECT_ROOT = _SCRIPT_DIR.parent
sys.path.insert(0, str(_PROJECT_ROOT))

# ---------------------------------------------------------------------------
# Trait wiring map: trait name -> (import_path, symbol)
# ---------------------------------------------------------------------------
TRAIT_WIRING: Dict[str, Tuple[str, str]] = {
    "action_roll": ("codex.core.services.fitd_engine", "FITDActionRoll"),
    "pbta_roll": ("codex.core.services.pbta_engine", "PbtAActionRoll"),
    "stress_track": ("codex.core.services.fitd_engine", "StressClock"),
    "faction_clocks": ("codex.core.services.fitd_engine", "FactionClock"),
    "doom_clock": ("codex.core.mechanics.clock", "DoomClock"),
    "spatial_dungeon": ("codex.spatial.map_engine", "CodexMapEngine"),
    "conditions": ("codex.core.mechanics.conditions", "ConditionTracker"),
    "initiative": ("codex.core.mechanics.initiative", "InitiativeTracker"),
    "progression_xp": ("codex.core.mechanics.progression", "ProgressionTracker"),
    "rest": ("codex.core.mechanics.rest", "RestManager"),
}

# ---------------------------------------------------------------------------
# Template helpers
# ---------------------------------------------------------------------------

_SPATIAL_ENGINE_TEMPLATE = '''\
# AUTO-GENERATED by scaffold_engine.py -- customize below
"""
{system_id} — Spatial Dungeon Engine
{ruler}
Auto-scaffolded from system_manifest.json.
Extend {base_class} with system-specific methods below.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from codex.core.engines.spatial_base import SpatialEngineBase
{extra_imports}


# =========================================================================
# CHARACTER
# =========================================================================

@dataclass
class {class_name}Character:
    """A {display_name} player character."""
    name: str
    setting_id: str = ""
{char_stat_fields}

    def is_alive(self) -> bool:
        return True

    def to_dict(self) -> dict:
        return {{k: getattr(self, k) for k in self.__dataclass_fields__}}

    @classmethod
    def from_dict(cls, data: dict) -> "{class_name}Character":
        return cls(**{{k: data[k] for k in cls.__dataclass_fields__ if k in data}})


# =========================================================================
# ENGINE
# =========================================================================

class {class_name}Engine(SpatialEngineBase):
    """{display_name} spatial dungeon engine."""

    system_id = "{system_id}"
    system_family = "{system_family}"
    display_name = "{display_name}"

    def __init__(self) -> None:
        super().__init__()

    # ── Abstract hook implementations ─────────────────────────────────

    def _create_character(self, name: str, **kwargs) -> {class_name}Character:
        """Create a {class_name}Character.

        Args:
            name: Character name.
            **kwargs: Stat overrides.

        Returns:
            New {class_name}Character instance.
        """
        return {class_name}Character(name=name, **kwargs)

    def _get_adapter(self, **kwargs) -> Any:
        """Return a RulesetAdapter for dungeon content injection.

        TODO: Replace with a system-specific RulesetAdapter subclass.

        Returns:
            A minimal adapter instance.
        """
        # TODO: implement a proper RulesetAdapter for {system_id}
        from codex.spatial.map_engine import ContentInjector
        class _Stub:
            def __init__(self):
                self.rng = __import__("random").Random()
            def populate_room(self, room):
                from codex.spatial.map_engine import PopulatedRoom
                return PopulatedRoom(geometry=room, content={{
                    "description": f"Room {{room.id}}",
                    "enemies": [], "loot": [], "hazards": [],
                }})
        return _Stub()


# =========================================================================
# ENGINE REGISTRATION
# =========================================================================

try:
    from codex.core.engine_protocol import register_engine
    register_engine("{system_id}", {class_name}Engine)
except ImportError:
    pass
'''

_NARRATIVE_ENGINE_TEMPLATE = '''\
# AUTO-GENERATED by scaffold_engine.py -- customize below
"""
{system_id} — Narrative/Scene Engine
{ruler}
Auto-scaffolded from system_manifest.json.
Extend {base_class} with system-specific methods below.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Optional

from codex.core.engines.narrative_base import NarrativeEngineBase
{extra_imports}


# =========================================================================
# CHARACTER
# =========================================================================

@dataclass
class {class_name}Character:
    """A {display_name} player character."""
    name: str
    setting_id: str = ""
{char_stat_fields}

    def is_alive(self) -> bool:
        return True

    def to_dict(self) -> dict:
        return {{k: getattr(self, k) for k in self.__dataclass_fields__}}

    @classmethod
    def from_dict(cls, data: dict) -> "{class_name}Character":
        return cls(**{{k: data[k] for k in cls.__dataclass_fields__ if k in data}})


# =========================================================================
# ENGINE
# =========================================================================

class {class_name}Engine(NarrativeEngineBase):
    """{display_name} narrative engine."""

    system_id = "{system_id}"
    system_family = "{system_family}"
    display_name = "{display_name}"

    def __init__(self) -> None:
        super().__init__()

    # ── Abstract hook implementations ─────────────────────────────────

    def _create_character(self, name: str, **kwargs) -> {class_name}Character:
        """Create a {class_name}Character.

        Args:
            name: Character name.
            **kwargs: Stat overrides.

        Returns:
            New {class_name}Character instance.
        """
        setting_id = kwargs.pop("setting_id", self.setting_id)
        return {class_name}Character(name=name, setting_id=setting_id, **kwargs)

    def _get_command_registry(self) -> Dict[str, Callable]:
        """Return the command registry for this engine.

        Returns:
            Dict mapping command names to handler methods.
        """
        return {{
            "roll": self._cmd_roll_action,
            "stress": self._cmd_crew_stress,
            "clocks": self._cmd_clocks,
        }}

    def _format_status(self) -> str:
        """Return human-readable engine status.

        Returns:
            Status string.
        """
        lead = self.party[0] if self.party else None
        return (
            f"{{self.display_name}} | Lead: {{lead.name if lead else 'None'}} "
            f"| Party: {{len(self.party)}}"
        )


# =========================================================================
# ENGINE REGISTRATION
# =========================================================================

try:
    from codex.core.engine_protocol import register_engine
    register_engine("{system_id}", {class_name}Engine)
except ImportError:
    pass
'''

_BESTIARY_TEMPLATE = {
    "_comment": "AUTO-GENERATED by scaffold_engine.py -- populate from source PDF",
    "system_id": "{system_id}",
    "tiers": {
        "1": [],
        "2": [],
        "3": [],
        "4": []
    }
}

_LOOT_TEMPLATE = {
    "_comment": "AUTO-GENERATED by scaffold_engine.py -- populate from source PDF",
    "system_id": "{system_id}",
    "tiers": {
        "1": [],
        "2": [],
        "3": [],
        "4": []
    }
}

_TEST_TEMPLATE = '''\
# AUTO-GENERATED by scaffold_engine.py -- customize below
"""
tests/test_{system_id}_engine.py — Smoke tests for {display_name} engine.

Tests:
  - Engine instantiation
  - Character creation
  - Command dispatch (roll, status)
  - Save / load round-trip
  - Action roll (if applicable)
"""

import json
import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))


# ---------------------------------------------------------------------------
# Import guard — skip if engine not yet implemented
# ---------------------------------------------------------------------------
try:
    from codex.games.{system_id} import {class_name}Engine, {class_name}Character
    _ENGINE_AVAILABLE = True
except ImportError:
    _ENGINE_AVAILABLE = False

pytestmark = pytest.mark.skipif(
    not _ENGINE_AVAILABLE,
    reason="codex.games.{system_id} not yet importable",
)


# =========================================================================
# Instantiation
# =========================================================================

class TestInstantiation:

    def test_engine_instantiation(self):
        engine = {class_name}Engine()
        assert engine.system_id == "{system_id}"

    def test_engine_display_name(self):
        engine = {class_name}Engine()
        assert engine.display_name == "{display_name}"

    def test_create_character(self):
        engine = {class_name}Engine()
        char = engine.create_character("TestHero")
        assert char.name == "TestHero"
        assert engine.character is char
        assert char in engine.party


# =========================================================================
# Command Dispatch
# =========================================================================

class TestCommandDispatch:

    def test_status_command(self):
        engine = {class_name}Engine()
        engine.create_character("Protagonist")
        result = engine.handle_command("status")
        assert isinstance(result, str)
        assert len(result) > 0

    def test_unknown_command(self):
        engine = {class_name}Engine()
        result = engine.handle_command("xyzzy_unknown")
        assert "Unknown" in result or "unknown" in result


# =========================================================================
# Save / Load round-trip
# =========================================================================

class TestSaveLoad:

    def test_save_returns_dict(self):
        engine = {class_name}Engine()
        engine.create_character("Saver")
        state = engine.save_state()
        assert isinstance(state, dict)
        assert state.get("system_id") == "{system_id}"

    def test_load_restores_character(self):
        engine = {class_name}Engine()
        engine.create_character("LoadMe")
        state = engine.save_state()

        engine2 = {class_name}Engine()
        engine2.load_state(state)
        assert engine2.character is not None
        assert engine2.character.name == "LoadMe"

    def test_save_state_is_json_serializable(self):
        engine = {class_name}Engine()
        engine.create_character("JSONCheck")
        state = engine.save_state()
        # Should not raise
        json.dumps(state)
'''

# ---------------------------------------------------------------------------
# Manifest discovery
# ---------------------------------------------------------------------------

def find_manifest(system_id: str) -> Optional[Path]:
    """Locate system_manifest.json for a given system_id.

    Search order:
        1. codex/games/{system_id}/system_manifest.json
        2. vault/{system_id}/system_manifest.json
        3. Recursive vault search for any system_manifest.json with matching system_id

    Args:
        system_id: The system identifier to search for.

    Returns:
        Path to the manifest file, or None if not found.
    """
    candidates = [
        _PROJECT_ROOT / "codex" / "games" / system_id / "system_manifest.json",
        _PROJECT_ROOT / "vault" / system_id / "system_manifest.json",
    ]
    for path in candidates:
        if path.exists():
            return path

    vault = _PROJECT_ROOT / "vault"
    if vault.exists():
        for manifest_path in vault.rglob("system_manifest.json"):
            try:
                data = json.loads(manifest_path.read_text(encoding="utf-8"))
                if data.get("system_id") == system_id:
                    return manifest_path
            except (json.JSONDecodeError, OSError):
                continue

    return None


def load_manifest(manifest_path: Path) -> dict:
    """Load and parse a system manifest JSON file.

    Args:
        manifest_path: Path to system_manifest.json.

    Returns:
        Parsed manifest dict.

    Raises:
        SystemExit: If the file cannot be read or parsed.
    """
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
        return data
    except (json.JSONDecodeError, OSError) as exc:
        print(f"ERROR: Cannot read manifest at {manifest_path}: {exc}", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Code generation helpers
# ---------------------------------------------------------------------------

def _to_class_name(system_id: str) -> str:
    """Convert system_id to a CamelCase class name prefix.

    E.g. 'my_system' -> 'MySystem', 'pbta' -> 'Pbta'

    Args:
        system_id: The system identifier string.

    Returns:
        CamelCase string.
    """
    return "".join(word.capitalize() for word in system_id.replace("-", "_").split("_"))


def _build_extra_imports(traits: List[str]) -> str:
    """Build import lines for the traits declared in the manifest.

    Args:
        traits: List of trait name strings from manifest.

    Returns:
        Newline-separated import statements string.
    """
    imports: Dict[str, List[str]] = {}
    for trait in traits:
        if trait in TRAIT_WIRING:
            module, symbol = TRAIT_WIRING[trait]
            imports.setdefault(module, []).append(symbol)

    lines = []
    for module, symbols in sorted(imports.items()):
        lines.append(f"from {module} import {', '.join(sorted(symbols))}")
    return "\n".join(lines)


def _build_char_stat_fields(char_stats: List[str]) -> str:
    """Build dataclass field lines for declared character_stats.

    Args:
        char_stats: List of stat name strings from manifest.

    Returns:
        Indented dataclass field lines (4-space indent).
    """
    if not char_stats:
        return "    # TODO: add character stat fields"
    lines = []
    for stat in char_stats:
        lines.append(f"    {stat}: int = 0")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# File generation
# ---------------------------------------------------------------------------

def generate_engine_file(
    system_id: str,
    manifest: dict,
    engine_dir: Path,
    force: bool = False,
) -> Path:
    """Generate the engine __init__.py file.

    Args:
        system_id: The system identifier.
        manifest: Parsed manifest dict.
        engine_dir: Target directory (codex/games/{system_id}/).
        force: If True, overwrite existing file.

    Returns:
        Path to the generated file.

    Raises:
        SystemExit: If file exists and force is False.
    """
    target = engine_dir / "__init__.py"
    if target.exists() and not force:
        print(
            f"ERROR: {target} already exists. Use --force to overwrite.",
            file=sys.stderr,
        )
        sys.exit(2)

    engine_dir.mkdir(parents=True, exist_ok=True)

    primary_loop = manifest.get("primary_loop", "scene_navigation")
    traits: List[str] = manifest.get("engine_traits", [])
    char_stats: List[str] = manifest.get("character_stats", [])
    display_name: str = manifest.get("display_name", system_id.title())
    system_family: str = manifest.get("system_family", system_id.upper())

    class_name = _to_class_name(system_id)
    extra_imports = _build_extra_imports(traits)
    char_stat_fields = _build_char_stat_fields(char_stats)
    ruler = "=" * (len(system_id) + 30)

    if primary_loop == "spatial_dungeon":
        base_class = "SpatialEngineBase"
        template = _SPATIAL_ENGINE_TEMPLATE
    else:
        base_class = "NarrativeEngineBase"
        template = _NARRATIVE_ENGINE_TEMPLATE

    content = template.format(
        system_id=system_id,
        class_name=class_name,
        base_class=base_class,
        display_name=display_name,
        system_family=system_family,
        extra_imports=extra_imports if extra_imports else "",
        char_stat_fields=char_stat_fields,
        ruler=ruler,
    )

    target.write_text(content, encoding="utf-8")
    try:
        display_path = target.relative_to(_PROJECT_ROOT)
    except ValueError:
        display_path = target
    print(f"  Created: {display_path}")
    return target


def generate_config_template(
    system_id: str,
    category: str,
    template_data: dict,
    force: bool = False,
) -> Path:
    """Generate an empty config JSON template.

    Args:
        system_id: The system identifier.
        category: Config category (e.g. 'bestiary', 'loot').
        template_data: The template dict to serialize.
        force: If True, overwrite existing file.

    Returns:
        Path to the generated file.
    """
    config_dir = _PROJECT_ROOT / "config" / category
    config_dir.mkdir(parents=True, exist_ok=True)
    target = config_dir / f"{system_id}.json"

    if target.exists() and not force:
        print(f"  Skipped (exists): config/{category}/{system_id}.json")
        return target

    filled = json.loads(
        json.dumps(template_data).replace('"{system_id}"', f'"{system_id}"')
    )
    target.write_text(
        json.dumps(filled, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    print(f"  Created: config/{category}/{system_id}.json")
    return target


def generate_test_file(
    system_id: str,
    manifest: dict,
    tests_dir: Path,
    force: bool = False,
) -> Path:
    """Generate the smoke test file.

    Args:
        system_id: The system identifier.
        manifest: Parsed manifest dict.
        tests_dir: The tests/ directory.
        force: If True, overwrite existing file.

    Returns:
        Path to the generated file.
    """
    target = tests_dir / f"test_{system_id}_engine.py"

    if target.exists() and not force:
        print(
            f"  Skipped (exists): tests/test_{system_id}_engine.py",
        )
        return target

    display_name: str = manifest.get("display_name", system_id.title())
    class_name = _to_class_name(system_id)

    content = _TEST_TEMPLATE.format(
        system_id=system_id,
        class_name=class_name,
        display_name=display_name,
    )

    tests_dir.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")
    print(f"  Created: tests/test_{system_id}_engine.py")
    return target


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    """Entry point for the scaffold_engine CLI."""
    parser = argparse.ArgumentParser(
        description="Scaffold a new game engine from a system manifest.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=dedent(__doc__),
    )
    parser.add_argument("system_id", help="System identifier (e.g. 'myworld')")
    parser.add_argument(
        "--force",
        action="store_true",
        default=False,
        help="Overwrite existing engine file if present",
    )
    parser.add_argument(
        "--manifest",
        type=str,
        default=None,
        help="Explicit path to system_manifest.json (overrides auto-search)",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        default=False,
        help="Show what would be generated without writing files",
    )

    args = parser.parse_args()
    system_id: str = args.system_id

    print(f"Scaffolding engine for: {system_id}")

    # Locate manifest
    if args.manifest:
        manifest_path = Path(args.manifest).resolve()
        if not manifest_path.exists():
            print(f"ERROR: Manifest not found at {args.manifest}", file=sys.stderr)
            sys.exit(1)
    else:
        manifest_path = find_manifest(system_id)
        if manifest_path is None:
            print(
                f"ERROR: No system_manifest.json found for '{system_id}'.\n"
                f"  Searched: codex/games/{system_id}/, vault/{system_id}/, vault/**",
                file=sys.stderr,
            )
            sys.exit(1)

    print(f"  Manifest: {manifest_path.relative_to(_PROJECT_ROOT)}")
    manifest = load_manifest(manifest_path)

    if args.dry_run:
        print("\n[DRY RUN] Would generate:")
        print(f"  codex/games/{system_id}/__init__.py")
        print(f"  config/bestiary/{system_id}.json")
        print(f"  config/loot/{system_id}.json")
        print(f"  tests/test_{system_id}_engine.py")
        print(f"\nManifest summary:")
        print(f"  display_name: {manifest.get('display_name', '?')}")
        print(f"  engine_type:  {manifest.get('engine_type', '?')}")
        print(f"  primary_loop: {manifest.get('primary_loop', '?')}")
        print(f"  traits:       {manifest.get('engine_traits', [])}")
        print(f"  resolution:   {manifest.get('resolution_mechanic', '?')}")
        sys.exit(0)

    engine_dir = _PROJECT_ROOT / "codex" / "games" / system_id
    tests_dir = _PROJECT_ROOT / "tests"

    print("\nGenerating files:")
    generate_engine_file(system_id, manifest, engine_dir, force=args.force)
    generate_config_template(
        system_id,
        "bestiary",
        {
            "_comment": "AUTO-GENERATED by scaffold_engine.py -- populate from source PDF",
            "system_id": system_id,
            "tiers": {"1": [], "2": [], "3": [], "4": []},
        },
        force=args.force,
    )
    generate_config_template(
        system_id,
        "loot",
        {
            "_comment": "AUTO-GENERATED by scaffold_engine.py -- populate from source PDF",
            "system_id": system_id,
            "tiers": {"1": [], "2": [], "3": [], "4": []},
        },
        force=args.force,
    )
    generate_test_file(system_id, manifest, tests_dir, force=args.force)

    print(f"\nDone! Next steps:")
    print(f"  1. Customize codex/games/{system_id}/__init__.py — implement _get_adapter()")
    print(f"  2. Populate config/bestiary/{system_id}.json from source PDF")
    print(f"  3. Populate config/loot/{system_id}.json from source PDF")
    print(f"  4. Run: python -m pytest tests/test_{system_id}_engine.py -v")


if __name__ == "__main__":
    main()
